### PR TITLE
Upgrades to timenorm 1.0.1 from Maven Central

### PR DESCRIPTION
**Pull request by bethard**

### CODE REVIEW

**Comment by kwalcock** [comment]
Similarly,

[21_i8343en.txt](https://github.com/clulab/eidos/files/3487320/21_i8343en.txt)

```
Exception in thread "main" java.lang.UnsupportedOperationException: Cannot parse empty token sequence
	at org.clulab.timenorm.scfg.SynchronousParser.parseAll(SynchronousParser.scala:35)
	at org.clulab.timenorm.scfg.SynchronousParser.parseAll(SynchronousParser.scala:24)
	at org.clulab.timenorm.scate.WordsToNumber.apply(WordsToNumber.scala:24)
	at org.clulab.timenorm.scate.TemporalNeuralParser.$anonfun$inferProperties$1(TemporalNeuralParser.scala:307)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:178)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike.map(SetLike.scala:101)
	at scala.collection.SetLike.map$(SetLike.scala:101)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at org.clulab.timenorm.scate.TemporalNeuralParser.inferProperties(TemporalNeuralParser.scala:293)
	at org.clulab.timenorm.scate.TemporalNeuralParser.$anonfun$parseBatchToXML$5(TemporalNeuralParser.scala:170)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
	at org.clulab.timenorm.scate.TemporalNeuralParser.$anonfun$parseBatchToXML$3(TemporalNeuralParser.scala:164)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:191)
	at org.clulab.timenorm.scate.TemporalNeuralParser.parseBatchToXML(TemporalNeuralParser.scala:163)
	at org.clulab.wm.eidos.context.TimeNormFinder.parseBatch(TimeNormFinder.scala:88)
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$14(TimeNormFinder.scala:173)
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$14$adapted(TimeNormFinder.scala:173)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:473)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:479)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:310)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:308)
	at scala.collection.AbstractIterator.to(Iterator.scala:1417)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:302)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1417)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:289)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:283)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1417)
	at org.clulab.wm.eidos.context.TimeNormFinder.find(TimeNormFinder.scala:174)
	at org.clulab.wm.eidos.EidosSystem.$anonfun$extractFrom$1(EidosSystem.scala:209)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at org.clulab.wm.eidos.EidosSystem.extractFrom(EidosSystem.scala:208)
	at org.clulab.wm.eidos.EidosSystem.extractFromDoc(EidosSystem.scala:176)
	at org.clulab.wm.eidos.EidosSystem.extractFromText(EidosSystem.scala:151)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$2(ExtractFromDirectory.scala:27)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$2$adapted(ExtractFromDirectory.scala:23)
	at org.clulab.wm.eidos.utils.Closer$.liftedTree1$1(Closer.scala:20)
	at org.clulab.wm.eidos.utils.Closer$.autoClose(Closer.scala:19)
	at org.clulab.wm.eidos.utils.Closer$AutoCloser.autoClose(Closer.scala:60)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$1(ExtractFromDirectory.scala:23)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$1$adapted(ExtractFromDirectory.scala:20)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:142)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by kwalcock** [comment]
Two more files, for a total of 3 out of 52, had this "Cannot parse empty token sequence" problem, so it's fairly common.

**Comment by kwalcock** [comment]
P.S. Because this branch still has that elasticsearch in it, it is actually using Lucene 7.0.0.  That may be reason for some strange behavior.

**Comment by bethard** [comment]
Thanks as always for running these branches on all these other files. Hopefully the 1.0.1 version corrects the issue?

**Comment by kwalcock** [comment]
Thanks for the quick turnaround time.  It seems to have fixed the problem.  It would be nice if the Scala compiler (optionally) kept track of exceptions better.

Between the first run of this branch and the second, some geoIDs changed for no apparent reason.  Below is a list.  I still don't know why this happens, but it can make regression testing difficult and maybe cause different computers to get different answers.  I don't think it's related to this PR, though.

```
2_

prev
        "text" : "IFPRI",
        "geoID" : "8792143"

next
        "text" : "IFPRI",
        "geoID" : "1862012"

25_

prev
        "text" : "Ganyiel",
        "geoID" : "720194"

next
        "text" : "Ganyiel",
        "geoID" : "10593051"

prev
        "text" : "PoCs",
        "geoID" : "10607161"

next
        "text" : "PoCs",
        "geoID" : "6692234"

30_

prev
        "text" : "Ganyiel",
        "geoID" : "720194"

next
        "text" : "Ganyiel",
        "geoID" : "10593051"

49_

prev
        "text" : "Greater",
        "geoID" : "8806003"

next
        "text" : "Greater",
        "geoID" : "8585724"

5_

prev
        "text" : "Great",
        "geoID" : "3013465"

next
        "text" : "Great",
        "geoID" : "1140025"

9_

prev
        "text" : "States",
        "geoID" : "3522281"

next
        "text" : "States",
        "geoID" : "734014"
```

**Comment by bethard** [comment]
If you can find a way to reliably get two runs to produce different geoIDs, please file a new issue and assign it to me. I can then try to find a way to give geonorm a more stable sort.

**Pull request merged**
