### PR TITLE
Zheng' tests, merge mentions.

### PR DESCRIPTION
**Pull request by ZhengTang1120**

### CODE REVIEW

**Comment by kwalcock** [comment]
It is my turn to be confused.  There is only a very small number of changes in this PR.  Did that Revert not work as expected or are the local and server versions somehow mixed up?

**Comment by ZhengTang1120** [comment]
I am confused too, I assume that it only shows the changes compare to my previous PR(which was reverted). Because I checked the my unit tests, they are labeled as "failingTest" in master but "passingTest" in my PR.

**Comment by kwalcock** [comment]
The changes haven't been merged into master yet, so they wouldn't be changed to passing there.  You are expecting a lot of changes to EidosActions.scala, right?

**Comment by ZhengTang1120** [comment]
Yes

**Comment by kwalcock** [comment]
This did not get all the changes.  I'm trying again.  The version you want is in the zheng_test branch with the number 160d2d1, I assume.

**Comment by ZhengTang1120** [comment]
I think I got the problem here. Because GitHub thinks that my branch is behind master, so it treats all my changes as happened before last commit in master.

**Comment by kwalcock** [comment]
I'm not sure about that, but I manually moved the changes to a branch kwalcock_redo_zheng_test that have all the changes up through 160d2d1 and it has passed the tests locally.  Your branch can be behind because Becky has since checked things in and that would explain that part.

**Comment by kwalcock** [comment]
I take that back.  She didn't do a PR yet on master.

**Comment by ZhengTang1120** [comment]
I found a way to solve this, I made a new branch from master and then apply all the changes to this new branch. It seems works.

**Comment by ZhengTang1120** [comment]
One thing I want to make sure is that besides the un_ontology.yml, there is no changes from other people, right?

**Comment by kwalcock** [comment]
I was wrong again.  Becky had made the change you found.  Yes, I think it's the only one.  I'll compare your result with mine before OKing the PR.  Thanks.

**Comment by ZhengTang1120** [comment]
Sorry for the inconvenient and all these extra work. I think my new branch just did the same thing as you do. I already put a PR there. Thanks!

**Comment by bsharpataz** [comment]
Guys, thanks for working through this!

**Comment by kwalcock** [comment]
I'll merge it momentarily after double checking then look at what else is waiting.

**Pull request merged**
