### PR TITLE
Uses tensorflow-java to load geonorm model instead of deeplearning4j

### PR DESCRIPTION
**Pull request by bethard**
Also revises code to process all document sentences in a batch, rather than sentence-by-sentence.

### CODE REVIEW

**Comment by kwalcock** [comment]
I'm checking whether this can happen twice in a row, but in the meantime the error message is being pasted here.

```
12:17:15.470 [scala-execution-context-global-13] INFO  org.clulab.wm.eidos.utils.Sourcer$ - Sourcing file ..\corpora\Doc52\txt\45_wfp278542.txt
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 20
	at org.clulab.wm.eidos.document.EidosDocument.$anonfun$parseGeoNorm$5(EidosDocument.scala:186)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
	at org.clulab.wm.eidos.document.EidosDocument.$anonfun$parseGeoNorm$3(EidosDocument.scala:182)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
	at org.clulab.wm.eidos.document.EidosDocument.parseGeoNorm(EidosDocument.scala:181)
	at org.clulab.wm.eidos.document.EidosDocument.$anonfun$parseGeoNorm$8(EidosDocument.scala:201)
	at scala.Option.map(Option.scala:146)
	at org.clulab.wm.eidos.document.EidosDocument.parseGeoNorm(EidosDocument.scala:201)
	at org.clulab.wm.eidos.EidosSystem.annotateDoc(EidosSystem.scala:153)
	at org.clulab.wm.eidos.EidosSystem.annotate(EidosSystem.scala:165)
	at org.clulab.wm.eidos.EidosSystem.extractFromText(EidosSystem.scala:182)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$2(ExtractFromDirectory.scala:27)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$2$adapted(ExtractFromDirectory.scala:23)
	at org.clulab.wm.eidos.utils.Closer$.liftedTree1$1(Closer.scala:20)
	at org.clulab.wm.eidos.utils.Closer$.autoClose(Closer.scala:19)
	at org.clulab.wm.eidos.utils.Closer$AutoCloser.autoClose(Closer.scala:60)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$1(ExtractFromDirectory.scala:23)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$1$adapted(ExtractFromDirectory.scala:20)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:142)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:166)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Suppressed: java.lang.ArrayIndexOutOfBoundsException: -1
		at scala.collection.mutable.WrappedArray$ofInt.apply$mcII$sp(WrappedArray.scala:178)
		at scala.collection.mutable.WrappedArray$ofInt.apply(WrappedArray.scala:178)
		at scala.collection.mutable.WrappedArray$ofInt.apply(WrappedArray.scala:175)
		at org.clulab.wm.eidos.context.GeoDisambiguateParser.$anonfun$findLocations$11(GeoDisambiguateParser.scala:87)
		at org.clulab.wm.eidos.context.GeoDisambiguateParser.$anonfun$findLocations$11$adapted(GeoDisambiguateParser.scala:87)
		at scala.collection.TraversableLike$WithFilter.$anonfun$withFilter$1(TraversableLike.scala:800)
		at scala.collection.TraversableLike$WithFilter.$anonfun$withFilter$1$adapted(TraversableLike.scala:800)
		at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
		at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
		at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
		at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
		at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
		at org.clulab.wm.eidos.context.GeoDisambiguateParser.$anonfun$findLocations$9(GeoDisambiguateParser.scala:84)
		at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
		at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
		at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
		at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
		at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
		at org.clulab.wm.eidos.context.GeoDisambiguateParser.findLocations(GeoDisambiguateParser.scala:80)
		at org.clulab.wm.eidos.document.EidosDocument.parseGeoNorm(EidosDocument.scala:177)
		... 32 more
		Suppressed: java.lang.ArrayIndexOutOfBoundsException
	[CIRCULAR REFERENCE:java.lang.ArrayIndexOutOfBoundsException]
	[CIRCULAR REFERENCE:java.lang.ArrayIndexOutOfBoundsException]
```

**Comment by bethard** [comment]
Looks like that's happening at the line:
```
val charEndIndex = sentence.endOffsets(wordEndIndex - 1)
```
Is it possible that `.endOffsets` would have a different number of entires than the words in `.raw`?

**Comment by MihaiSurdeanu** [comment]
This should not happen. If it does, it is a clear bug.

**Comment by kwalcock** [comment]
Please stand by for a collection of files that exhibit the problem.  You're all too fast!

**Comment by kwalcock** [comment]
It seems to fail reliably on these attached files.  I'm using a newly checked out geonorm-tensorflow branch and testing on Windows, which shouldn't make a difference.  Would @bethard like to take the first stab at it?  It sounds like it might not be related directly to the geo internals, so I can probably find it, especially if for some reason it doesn't reproduce.

[49_WFP-0000050282.txt](https://github.com/clulab/eidos/files/3292152/49_WFP-0000050282.txt)
[21_i8343en.txt](https://github.com/clulab/eidos/files/3292153/21_i8343en.txt)
[24_pnas.201409769.txt](https://github.com/clulab/eidos/files/3292154/24_pnas.201409769.txt)
[26_South_Sudan_2018_Humanitarian_Needs_Overview.txt](https://github.com/clulab/eidos/files/3292155/26_South_Sudan_2018_Humanitarian_Needs_Overview.txt)
[31_South_Sudan_2018_Humanitarian_Needs_Overview.txt](https://github.com/clulab/eidos/files/3292156/31_South_Sudan_2018_Humanitarian_Needs_Overview.txt)

**Comment by kwalcock** [comment]
BTW I kind of like this construction and may start using it, expecially if it's not this.textOpt.  Thanks for the nice style.

```scala
val Some(text) = this.text
```

**Comment by bethard** [comment]
Yes, I'll look at these now. How are you running those texts through Eidos? That is, what command should I be using?

**Comment by kwalcock** [comment]
I was using an IntelliJ run configuration with main class `org.clulab.wm.eidos.apps.ExtractFromDirectory` and then some arguments specifying a directory for the text and jsonld files: `../corpora/Doc52/txtbad ../corpora/Doc52/jsonld-geotensor-geotime` that will be different on your computer.  I also have -Xmx18g with a full contingent of Xs.  It was basically a regression test.  There might be a simpler option.

**Comment by bethard** [comment]
Thanks for finding these files and the instructions on how to test against them. I think I have found the bug (an issue in how I was padding the batches).

**Comment by kwalcock** [comment]
That took care of at least one document, but there might be one more problem.  The line
```scala
        if wordPrediction == B_LOC || (wordPrediction == I_LOC && wordPredictions(wordIndex - 1) == O_LOC)
```
runs even when wordIndex == 0.  The previous version had an additional check something like
```scala
              startIndex == 0 || // labels start immediately on I_LOC
                  labelIndexes(startIndex - 1) == GeoDisambiguateParser.O_LOC // or without B_LOC or I_LOC preceeding

```
Would you "like to do the honors"?



```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at scala.collection.mutable.WrappedArray$ofInt.apply$mcII$sp(WrappedArray.scala:178)
	at scala.collection.mutable.WrappedArray$ofInt.apply(WrappedArray.scala:178)
	at scala.collection.mutable.WrappedArray$ofInt.apply(WrappedArray.scala:175)
	at org.clulab.wm.eidos.context.GeoDisambiguateParser.$anonfun$findLocations$11(GeoDisambiguateParser.scala:87)
	at org.clulab.wm.eidos.context.GeoDisambiguateParser.$anonfun$findLocations$11$adapted(GeoDisambiguateParser.scala:87)
	at scala.collection.TraversableLike$WithFilter.$anonfun$withFilter$1(TraversableLike.scala:800)
	at scala.collection.TraversableLike$WithFilter.$anonfun$withFilter$1$adapted(TraversableLike.scala:800)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
	at org.clulab.wm.eidos.context.GeoDisambiguateParser.$anonfun$findLocations$9(GeoDisambiguateParser.scala:84)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
	at org.clulab.wm.eidos.context.GeoDisambiguateParser.findLocations(GeoDisambiguateParser.scala:80)
	at org.clulab.wm.eidos.document.EidosDocument.parseGeoNorm(EidosDocument.scala:177)
	at org.clulab.wm.eidos.document.EidosDocument.$anonfun$parseGeoNorm$8(EidosDocument.scala:201)
	at scala.Option.map(Option.scala:146)
	at org.clulab.wm.eidos.document.EidosDocument.parseGeoNorm(EidosDocument.scala:201)
	at org.clulab.wm.eidos.EidosSystem.annotateDoc(EidosSystem.scala:153)
	at org.clulab.wm.eidos.EidosSystem.annotate(EidosSystem.scala:165)
	at org.clulab.wm.eidos.EidosSystem.extractFromText(EidosSystem.scala:182)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$2(ExtractFromDirectory.scala:27)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$2$adapted(ExtractFromDirectory.scala:23)
	at org.clulab.wm.eidos.utils.Closer$.liftedTree1$1(Closer.scala:20)
	at org.clulab.wm.eidos.utils.Closer$.autoClose(Closer.scala:19)
	at org.clulab.wm.eidos.utils.Closer$AutoCloser.autoClose(Closer.scala:60)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$1(ExtractFromDirectory.scala:23)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$1$adapted(ExtractFromDirectory.scala:20)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.delayedEndpoint$org$clulab$wm$eidos$apps$ExtractFromDirectory$1(ExtractFromDirectory.scala:20)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$delayedInit$body.apply(ExtractFromDirectory.scala:11)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.main(ExtractFromDirectory.scala:11)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory.main(ExtractFromDirectory.scala)
```

**Comment by bethard** [comment]
Yes, I'll fix it. How can I figure out exactly which part of the text is causing the error? I'd like to put a test in somewhere to make sure this doesn't come back.

**Comment by kwalcock** [comment]
I'd be tempted to add two lines of code like
```scala
if (wordPrediction == I_LOC && wordIndex == 0)
   println("Oh, no!")
```
and add a breakpoint on the second line.  Perhaps from there you can see what text text is causing the issue and see if it happens as well in a document with the single sentence.  That sentence might work well in a unit test.

**Comment by kwalcock** [comment]
It may go without saying, but just in case, nobody is waiting desperately for this code.  Have a Happy Father's Day!

**Comment by bethard** [comment]
Yeah, no rush on this. But I was able to narrow down a couple examples of text where the model consistently generated odd predictions (a sentence initial `I-LOC` tag, and `*-LOC` tags on the padding tokens for batch processing) wrote some tests for those, and updated the code to ensure those tests passed.

**Comment by kwalcock** [comment]
Thanks for the extra tests.  The new code makes it through all the documents now.  The text of a geoloc is improved over the old version
```scala
val prettyLocationPhrase = words.slice(startIndex, endIndex).mkString(" ")
```
which used the parsed words rather than the actual text.  Except for that and things that start at the beginning of the sentence, output matches previous version.

Merging...

**Pull request merged**
