### PR TITLE
Mitre tests on Doc3

### PR DESCRIPTION
**Pull request by ajaynagesh**
- Added unit tests for "EA_Seasonal_Monitor_2017_08_11" (Doc 3) -- overall 83 tests in 16 paragraphs
- Initially added the tests for the highlighted paragraphs
- Subsequently added the tests for all the remaining paragraphs (the numbering does not follow the paragraph numbers in the document, but within each of the above 2 categories they are sequential)
- Have added todos wherever I am not very sure or have some questions

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Becky, Keith: can you please review these?

**Comment by kwalcock** [comment]
Should the spelling of Vegetatoin be corrected to Vegetation even if it was wrong in the original?  Thanks for the tag change.

**Comment by MihaiSurdeanu** [comment]
Yes, let’s use correct language for now.

**Comment by kwalcock** [comment]
I hadn't actually noticed your comment about the typo, but I'm glad the issue has been addressed.  Thanks for finding the other one.  Have fun testing.

**Pull request merged**
