### PR TITLE
preserve path for expanded arguments

### PR DESCRIPTION
**Pull request by marcovzla**
addresses problem related to different extractions depending on spaces

### CODE REVIEW

**Comment by kwalcock** [comment]
Thanks for working so long, so late on this.  I can't say that I understand it (yet).  I would have expected changes to createEventChain, but the combination of changes to expandArguments and reintroduction of keepMostComplete must force createEventChain to produce the correct/singular answer.  Still, "head" there makes me worry and so does "hopefully," although I like the positive attitude.  At some point, perhaps after all the experimentation is finished, this code can be documented more thoroughly.

**Comment by kwalcock** [comment]
So, if it still looks good to you all this morning, I'll merge it :-)

**Comment by bsharpataz** [comment]
I'm for it, I'd love for @marcovzla  to see the general form on lines 496 to 499 and give some thumbs up or down... also, how easily can we check to see if applying this takes care of #417?

**Comment by kwalcock** [comment]
One could rewrite the hash function for Mentions, calculateHashCode, in a private copy of processors and then rerun Eidos on a large number of documents to make sure the answer doesn't change.  Adding - to the hash code might reverse all conversions from maps to lists.  That seems painful, though.

**Comment by kwalcock** [comment]
FWIW I'm doing the above, so nobody else needs to be.

**Comment by kwalcock** [comment]
I ran the unit tests and did quite a bit of regression tests on hundreds of files with the normal hash function and then the negation of it and see no differences in output with the fix, so I'm satisfied and will merge it finally (well, it was within a day, but it's holding up other older things).  @bsharpataz did need to adapt a test above, thanks, and there are differences in the output between before the fix and after the fix, but not very many.

For the GitHub record let me report that I also used a hash function that returns zero, creating a collision for every Mention.  This breaks the tests and changes quite a bit of the output.  The probable cause is this code in Mention:
```
  override def equals(that: Any): Boolean = that match {
    case that: Mention => that.canEqual(this) && this.hashCode == that.hashCode
    case _ => false
  }
```
It has been there for many years and I've just been crossing my fingers that there is never an important collision.  It doesn't seem to be noted as an issue in processors, so it will be added.

**Pull request merged**
