### PR TITLE
added dec from neg dep on nouns, duh.

### PR DESCRIPTION
**Pull request by bsharpataz**
shoulda done this way earlier...

### CODE REVIEW

**Comment by bsharpataz** [comment]
though... this sentence brought up a limitation to the negation handler:
“ Trade worsened during the conflict as there was no exchange of goods from Sudan and the other states of South Sudan , ” he added .

image

image

@MihaiSurdeanu how general do you think it is that if the `neg` dep lands on "no" then it's not negating the event?

**Comment by MihaiSurdeanu** [comment]
@bsharpataz: I don't know. I have *no* opinion if this decision *impacts* performance. (see the example? :))
Shouldn't we force the neg dependency to be headed by the predicate?

Also, why does this Correlation rule match here? Certainly a copulative verb is no indicator of correlation...

**Comment by bsharpataz** [comment]
re: "Shouldn't we force the neg dependency to be headed by the predicate?" 
I'm looking in this PR for negs off of nouns to count as "DEC" of that noun.  In the negation handler, I think that negs coming off of anything on the event token interval count, I ported from Reach, so I guess that was super intentional?

re: correlation -- the rule actually looks for a word with incoming advcl_as: `trigger = [incoming=advcl_as]`, just so happens it was "was" here.  The trigger here is less triggery than most rules... I could make a special action that removes the trigger and turns it into a RelationMention if you want...

**Comment by kwalcock** [comment]
Conclusion?  Go for it?

**Comment by MihaiSurdeanu** [comment]
Ok then!

I think this is reasonable then. Please merge.

**Pull request merged**
