### PR TITLE
Be nitpicky about it

### PR DESCRIPTION
**Pull request by kwalcock**
Document my magic number
Do a count once instead of filter.length
Try lazy val within method

### CODE REVIEW

**Comment by kwalcock** [comment]
I wonder if 5 or 6 is too low a value for the single char, especially given that most punctuation is a single char and has already been counted.  The period at the end of the sentence counts for one and pairs of quotes and parentheses count as two.

**Comment by BeckySharp** [comment]
nice thought, this is one of the reasons I love working with you.  I didn't
even think about it.
Maybe instead we should check for only _.isLetter and .length == 1 (if you
get my drift)

**Comment by kwalcock** [comment]
I would be (a little) more comfortable with that, I guess.  The previous sentence already has 6.

**Comment by kwalcock** [comment]
Quite a few tests are failing.  The first one I checked had filtered out this sentence:
```
Crisis (IPC Phase 3) is widespread and
Emergency (IPC Phase 4) outcomes exist in parts of Unity,
Western Bahr el Ghazal,
```
This was even after the change to the single letter condition.  The numbers probably need to be higher or the kinds of symbols different.

**Comment by BeckySharp** [comment]
OK, i'll look tomorrow, thanks for point this all out!

**Comment by kwalcock** [comment]
I could output the counts for each measurement and then look at their distribution for at least the tests so that they can be made to pass.  It might be a good idea to check a real corpus eventually.

**Comment by kwalcock** [comment]
Here it is for numSingleAlpha:

count | instances
-- | --
0 | 10384
1 | 666
2 | 92
3 | 8
4 | 1
5 | 0
6 | 0
7 | 0
8 | 0
9 | 0
10 | 0
11 | 0
12 | 0
13 | 0
14 | 0
15 | 2
16 | 0

**Comment by kwalcock** [comment]
The 33 and 15 are for the one sentence we're trying to avoid.

**Comment by kwalcock** [comment]
We know all the one-letter English words, don't we?  I and a.  Perhaps they should not be counted.

**Comment by kwalcock** [comment]
Maybe not count valid numbers and punctuation.  For purposes of ruling out the single sentence, numSingleAlpha < 10 is sufficient.  We're getting too many false fubars otherwise IMO.

**Comment by BeckySharp** [comment]
sounds fine to me

**Comment by kwalcock** [comment]
This code isn't as elegant as that of @BeckySharp, but it does pass the tests.

**Comment by kwalcock** [comment]
Do you think this is OK, @BeckySharp?  The numSingleAlpha from the table above looks like a more reliable indicator of a problem that causes the program to hang.  Because there are some valid 1-letter words in English that I wanted to take into account, the code changed location a little.

**Review by BeckySharp — APPROVED** [review]
Looks great, and yes I think that's a good litmus test.  If this were just an Object it wouldn't need to be passed around, but may not be as easily extensible.  then again, we may never need to extend it.  Either way, I totally approve and am simply adding my belated 1 cent. :)
thanks!

**Comment by kwalcock** [comment]
Good, valid point.  I flipped a coin.  Luckily it's only about three lines of code.  I imagined a table detector, graph detector, PDF problem detector, ways to combine them, plugins, and language specializations... that would eventually be easier if it was a class.  For today, it's close enough for me.

**Pull request merged**
