### PR TITLE
updated ontology to include interventions

### PR DESCRIPTION
**Pull request by bsharpataz**
fyi @ajaynagesh @ZhengTang1120

### CODE REVIEW

**Comment by bsharpataz** [comment]
- the '' I just took care of, thanks  
- The ones that seem "incorrect" come from the spreadsheet, e.g.:
image
(not that you can read that)
so... i am unsure what we should do, as this theoretically comes from the experts?
- why is `"hiv/aids" (line 185)` incorrect? it's under the antiretroviral node
- i merged the `i.e.` and `e.g.` lines up... but am not sure we should merge the e.g. ones... they're examples right?

**Comment by MihaiSurdeanu** [comment]
@bsharpataz: Should I review this again?

code should live under src/main/PROGRAMMING_LANGUAGE/...

**Comment by MihaiSurdeanu** [comment]
Ok

**Comment by kwalcock** [comment]
What are these things: `- ''`?  It seems like the rest of the file was made so that the names of the non-leaf nodes contain no spaces, but these do.  The directory tree is on a per project basis.  I'm starting to think that there needs to be a separate project for the preparation of materials.  I need to add a program to normalize vectors, another to remove duplicates from ontologies, maybe another to pre-serialize vectors and ontologies,...

**Comment by bsharpataz** [comment]
didn't all the '' get removed?

**Comment by bsharpataz** [comment]
@MihaiSurdeanu I made the changes we talked about, namely to move keywords to their own field and to add the synonym info from the other sheet.  I opted to do less processing of text here (i.e. stop words) and allow grounding to have at it.  Please review, at least to some degree and let me know if this will pass muster :)

**Comment by bsharpataz** [comment]
@kwalcock are we waiting on something before we merge this one?

**Comment by kwalcock** [comment]
Sorry, I hadn't notice the next set of changes.  Are keywords used by the program?  I assume this unknown field is ignored.  Should "e.g." or "i.e." or "and" be part of them, does it matter when they end with a comma or are missing spaces: "counselling,pep,"?  If you say it's OK,  I'll just click the button.

**Pull request merged**
