### PR TITLE
Update of DomainOntology

### PR DESCRIPTION
**Pull request by kwalcock**
This supports an OntologyNode (among other things)

### CODE REVIEW

**Comment by kwalcock** [comment]
This is a heads up, @ajaynagesh, to prevent unpleasant surprises.  I'm still doing some regression testing and have a small list of changes prending.  Nothing outside of this PR needs to change, as far as I know, but it does affect how this subsystem evolves.

**Comment by kwalcock** [comment]
I wonder whether Mihai was hinting at a format more like

- OntologyNode:
  - id:
    - 4
  - path:
    - /events/crisis
  - examples:
    - "crisis"
    - "emergency"
  - description:
    - "Some text"

where the paths are collapsed.  This might lend itself better to yaml processing.  The type of each node is known and one doesn't need to walk the tree.

**Comment by kwalcock** [comment]
I'm waiting to hear back about duplicate paths before completing testing.

**Comment by ajaynagesh** [comment]
Thanks for the heads up, @kwalcock! 

I have asked @ZhengTang1120 about the duplicate paths in the wdi ontology.

**Comment by MihaiSurdeanu** [comment]
@kwalcock: yes, that is exactly what I was hinting at.

**Comment by kwalcock** [comment]
I somehow heard that with my code ear and not the data ear.  Can the ontology team adjust the yaml file to such a format?  If need be I can change OntologyNode and DomainOntology.parseOntology to match.  The code is in pretty good shape to accommodate that.  Is the program that creates these yaml files in a reasonably managed state, I wonder?  We might not want it in GitHub, but is it being carefully guarded on a CluLab server?

**Comment by marcovzla** [comment]
One tweak to @kwalcock example that may be necessary is this:

```
- OntologyNode:
    id: 4
    path: /events/crisis
    examples:
      - "crisis"
      - "emergency"
    description: "Some text"
```

That would indicate that the value of `OntologyNode` is a dictionary with four keys. Leaving the dashes makes it a list of dictionaries.

**Comment by MihaiSurdeanu** [comment]
Good point.

@ajaynagesh or @kwalcock: can you please adjust the ontologies so they match this format?

**Comment by kwalcock** [comment]
Thanks.  I'm getting mixed up between JSON and yaml and just pseudocode.  I imagine that someone else is producing the file, though.  Whatever describes the data best and isn't too hard to ingest.

**Comment by kwalcock** [comment]
Here's a list of duplicates in WDI.  A unit test is finding these now.

/WDI/2005_PPP_conversion_factor/description
/WDI/Access_to_electricity/description
/WDI/Account_ownership_at_a_financial_institution_or_with_a_mobile-money-service_provider/description
/WDI/Adjusted_net_enrollment_rate/description
/WDI/Adjusted_net_savings/description
/WDI/Adolescents_out_of_school/description
/WDI/Age_dependency_ratio/description
/WDI/Agricultural_machinery/description
/WDI/Agriculture/description
/WDI/Air_transport/description
/WDI/All_education_staff_compensation/description
/WDI/Annual_freshwater_withdrawals/description
/WDI/Annualized_average_growth_rate_in_per_capita_real_survey_mean_consumption_or_income/description
/WDI/Average_grace_period_on_new_external_debt_commitments/description
/WDI/Average_grant_element_on_new_external_debt_commitments/description
/WDI/Average_interest_on_new_external_debt_commitments/description
/WDI/Average_maturity_on_new_external_debt_commitments/description
/WDI/Average_working_hours_of_children/description
/WDI/Binding_coverage/description
/WDI/Bound_rate/description
/WDI/Cause_of_death/description
/WDI/Central_government_debt/description
/WDI/Charges_for_the_use_of_intellectual_property/description
/WDI/Child_employment_in_agriculture/description
/WDI/Child_employment_in_manufacturing/description
/WDI/Child_employment_in_services/description
/WDI/Children_in_employment/description
/WDI/Children_out_of_school/description
/WDI/Commitments/description
/WDI/Communications/description
/WDI/Completeness_of_birth_registration/description
/WDI/Computer/description
/WDI/Condom_use/description
/WDI/Contraceptive_prevalence/description
/WDI/Contributing_family_workers/description
/WDI/Cost_of_business_start-up_procedures/description
/WDI/Cost_to_export/description
/WDI/Cost_to_import/description
/WDI/Currency_composition_of_PPG_debt/description
/WDI/Current_education_expenditure/description
/WDI/Debt_service_on_external_debt/description
/WDI/Disbursements_on_external_debt/description
/WDI/Educational_attainment/description
/WDI/Electricity_production_from_renewable_sources/description
/WDI/Employers/description
/WDI/Employment_in_agriculture/description
/WDI/Employment_in_industry/description
/WDI/Employment_in_services/description
/WDI/Employment_to_population_ratio/description
/WDI/External_debt_stocks/description
/WDI/Final_consumption_expenditure/description
/WDI/Foreign_direct_investment/description
/WDI/GDP/description
/WDI/GDP_per_capita/description
/WDI/GNI/description
/WDI/GNI_per_capita/description
/WDI/Government_expenditure_on_education/description
/WDI/Government_expenditure_per_student/description
/WDI/Gross_fixed_capital_formation/description
/WDI/Gross_intake_ratio_in_first_grade_of_primary_education/description
/WDI/Household_final_consumption_expenditure/description
/WDI/Immunization/description
/WDI/Industrial_design_applications/description
/WDI/Industry/description
/WDI/Inflation/description
/WDI/Informal_employment/description
/WDI/Interest_arrears/description
/WDI/Interest_payments_on_external_debt/description
/WDI/Interest_rescheduled/description
/WDI/Internally_displaced_persons/description
/WDI/International_tourism/description
/WDI/Labor_force/description
/WDI/Labor_force_participation_rate/description
/WDI/Labor_force_participation_rate_for_ages_15-24/description
/WDI/Labor_force_with_advanced_education/description
/WDI/Labor_force_with_basic_education/description
/WDI/Labor_force_with_intermediate_education/description
/WDI/Life_expectancy_at_birth/description
/WDI/Literacy_rate/description
/WDI/Lower_secondary_completion_rate/description
/WDI/Manufacturing/description
/WDI/Mortality_rate/description
/WDI/Net_bilateral_aid_flows_from_DAC_donors/description
/WDI/Net_financial_flows/description
/WDI/Net_flows_on_external_debt/description
/WDI/Net_incurrence_of_liabilities/description
/WDI/Net_intake_rate_in_grade_1/description
/WDI/Net_ODA_provided/description
/WDI/Net_official_flows_from_UN_agencies/description
/WDI/Net_transfers_on_external_debt/description
/WDI/Over-age_students/description
/WDI/Part_time_employment/description
/WDI/Patent_applications/description
/WDI/People_practicing_open_defecation/description
/WDI/People_using_at_least_basic_drinking_water_services/description
/WDI/People_using_at_least_basic_sanitation_services/description
/WDI/People_using_safely_managed_drinking_water_services/description
/WDI/People_using_safely_managed_sanitation_services/description
/WDI/People_with_basic_handwashing_facilities_including_soap_and_water/description
/WDI/Persistence_to_grade_5/description
/WDI/Persistence_to_last_grade_of_primary/description
/WDI/Personal_remittances/description
/WDI/PM2.5_air_pollution/description
/WDI/PM2.5_pollution/description
/WDI/PNG/description
/WDI/Population/description
/WDI/Population_ages_0-14/description
/WDI/Population_ages_0-4/description
/WDI/Population_ages_10-14/description
/WDI/Population_ages_15-19/description
/WDI/Population_ages_15-64/description
/WDI/Population_ages_20-24/description
/WDI/Population_ages_25-29/description
/WDI/Population_ages_30-34/description
/WDI/Population_ages_35-39/description
/WDI/Population_ages_40-44/description
/WDI/Population_ages_45-49/description
/WDI/Population_ages_50-54/description
/WDI/Population_ages_55-59/description
/WDI/Population_ages_5-9/description
/WDI/Population_ages_60-64/description
/WDI/Population_ages_65_and_above/description
/WDI/Population_ages_65-69/description
/WDI/Population_ages_70-74/description
/WDI/Population_ages_75-79/description
/WDI/Population_ages_80_and_above/description
/WDI/PPG/description
/WDI/PPP_conversion_factor/description
/WDI/Prevalence_of_HIV/description
/WDI/Prevalence_of_overweight/description
/WDI/Prevalence_of_severe_wasting/description
/WDI/Prevalence_of_stunting/description
/WDI/Prevalence_of_underweight/description
/WDI/Prevalence_of_wasting/description
/WDI/Primary_completion_rate/description
/WDI/Primary_education/description
/WDI/Principal_arrears/description
/WDI/Principal_repayments_on_external_debt/description
/WDI/Principal_rescheduled/description
/WDI/Progression_to_secondary_school/description
/WDI/Proportion_of_time_spent_on_unpaid_domestic_and_care_work/description
/WDI/Pupil-teacher_ratio/description
/WDI/Railways/description
/WDI/Repeaters/description
/WDI/Revenue/description
/WDI/School_enrollment/description
/WDI/Secondary_education/description
/WDI/Self-employed/description
/WDI/Share_of_tariff_lines_with_international_peaks/description
/WDI/Share_of_tariff_lines_with_specific_rates/description
/WDI/Share_of_youth_not_in_education/description
/WDI/Smoking_prevalence/description
/WDI/Start-up_procedures_to_register_a_business/description
/WDI/Stocks_traded/description
/WDI/Survey_mean_consumption_or_income_per_capita/description
/WDI/Survival_to_age_65/description
/WDI/Tariff_rate/description
/WDI/Taxes_on_income/description
/WDI/Time_required_to_start_a_business/description
/WDI/Time_to_export/description
/WDI/Time_to_import/description
/WDI/Trademark_applications/description
/WDI/Trained_teachers_in_lower_secondary_education/description
/WDI/Trained_teachers_in_preprimary_education/description
/WDI/Trained_teachers_in_primary_education/description
/WDI/Trained_teachers_in_secondary_education/description
/WDI/Trained_teachers_in_upper_secondary_education/description
/WDI/Undisbursed_external_debt/description
/WDI/Unemployment/description
/WDI/Unemployment_with_advanced_education/description
/WDI/Unemployment_with_basic_education/description
/WDI/Unemployment_with_intermediate_education/description
/WDI/Vulnerable_employment/description
/WDI/Wage_and_salaried_workers/description
/WDI/World_Bank/description

**Comment by MihaiSurdeanu** [comment]
@ajaynagesh, @ZhengTang1120: please address this after the conference deadline.

**Comment by kwalcock** [comment]
It seems like the ontology team has lots of other work to do.  I'm going to remove the test for duplicates so that this code can be checked in.  We can return to it later.

**Pull request merged**
