### PR TITLE
Canonical form

### PR DESCRIPTION
**Pull request by bsharpataz**
feel free to close PR or request changes, but here as a PR in case it's helpful

### CODE REVIEW

**Comment by kwalcock** [comment]
Thanks for the tests.  If it's OK, I'll move some code around to match what I was trying to describe.

**Comment by bsharpataz** [comment]
yep!  And I'll take note and try to learn from you! :)

**Comment by kwalcock** [comment]
Usually I would wait a day before messing with people's stuff, but we're in a hurry...  Common functionality remains in the base class and custom functionality is pushed down to derived classes, which obviates the need for the case statement.  You're welcome to change protected back to private.  I'm in the "private is premature pessimization" school, but it probably won't be important here.  Still, I could not resist.

**Comment by bsharpataz** [comment]
Thanks Keith!!

**Pull request merged**
