### PR TITLE
rough draft of readme

### PR DESCRIPTION
**Pull request by bsharpataz**
note -- I will submit the PR with the new files that this references now
(PR https://github.com/clulab/eidos/pull/90)

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
"small set of rules" => "grammar"

**Comment by kwalcock** [comment]
Also, good plan doing this PR separate from code changes!

**Comment by kwalcock** [comment]
And FWIW .\shell also works on certain machines.

**Comment by kwalcock** [comment]
If RAPShell => EidosShell, is there any problem leaving it in agro.demo, or should that be changed as well?

**Comment by MihaiSurdeanu** [comment]
We shouldn’t use the “agro” name anywhere in the software.

**Comment by bsharpataz** [comment]
Yes, I think we should move it, not just rename agro.  The actual directory
separation we have is largely meaningless. Keith, given that you were
thinking some subprojects I was hoping you steer me to repo goodness and
truth... or at least suggest an appropriate directory structure. :)

**Comment by kwalcock** [comment]
In something just submitted, I renamed it to eidos.demo and decided it wasn't too bad to have these Apps packaged in the same jar.  They provide examples of how to use the API.   I'm not sure about having these outside the org.clulab.wm namespace, however. and that goes for Utils.  However, one step at a time.

We might want to merge this one even though not quite complete in order to avoid merge conflicts.

**Comment by bsharpataz** [comment]
@kwalcock re: `And FWIW .\shell also works on certain machines.` -- I am not quite sure what you mean by this and how I should address it

**Comment by kwalcock** [comment]
I was vague.  It is .\shell for windows.  There is a shell.bat to take care of this.  Windows users will figure it out, so it may not be worth mentioning.  Are you ready to merge?  It's more perfect than what we have.

**Comment by bsharpataz** [comment]
I think it's ready to merge -- def better than what we have and @Mihai I
can continue to make any changes you want....?

**Comment by MihaiSurdeanu** [comment]
Yep, please merge.

**Pull request merged**
