### PR TITLE
Fix the missing diagram by producing expected json

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
You may press the button.

**Comment by marcovzla** [comment]
I see this fixes the error when there is no time or location. But does it actually renders something when it does? Maybe I don't understand brat syntax but I suspect it may not.

**Comment by kwalcock** [comment]
I tested with time and geolocations turned on and it shows at least the TimeExpression (as in https://github.com/clulab/eidos/blob/master/README.md).  I have yet to see a location in the diagram.  The code
```scala
        Json.arr(
          s"X$x",
          "x",
```
does look suspicious.

**Comment by marcovzla** [comment]
I'm pretty sure brat only handles `entities`, `events`, `triggers`, `attributes`, and `relations`, and any other key should be ignored

**Comment by marcovzla** [comment]
I suspect that `timexs` and `geoexps` are being ignored, and what gets rendered comes from `entities` or `events`

**Comment by kwalcock** [comment]
Perhaps it has been updated.

image

image

**Comment by EgoLaparra** [comment]
I think the brat part for Locations was not implemented. So, they shouldn't show up.

**Comment by kwalcock** [comment]
There is this code in main.js:
```javascript
        {
            "type"   : "GeoidPhrases",
            "labels" : ["GeoidPhrases", "GEOLOC"],
            // Blue is a nice colour for a person?
            //"bgColor": "thistle",
            "bgColor": geoLocationColor,
            // Use a slightly darker version of the bgColor for the border
            "borderColor": "darken"
         },
```

**Comment by kwalcock** [comment]
I'll go ahead and check it in though, so at least the time shows on master.  Thanks for your help. everyone.

**Pull request merged**
