### PR TITLE
icasa in the mapping files

### PR DESCRIPTION
**Pull request by bsharpataz**
sorry @adarshp thought I had this in already

### CODE REVIEW

**Comment by bsharpataz** [comment]
@kwalcock @adarshp @bgyori -- I/Keith can merge this as soon as we know that it won't screw you guys up for the eval...?

**Comment by bgyori** [comment]
This is fine with me

**Comment by adarshp** [comment]
Fine with me as well!

**Comment by bsharpataz** [comment]
👍

**Pull request merged**
