### PR TITLE
wip verbose grounding exporter

### PR DESCRIPTION
**Pull request by BeckySharp**

### CODE REVIEW

**Comment by BeckySharp** [comment]
@zupon do you know the status of this?

**Comment by zupon** [comment]
I'm not sure if we still need this? We didn't end up doing anything with it for the ontology augmentation exercise. Alternatively, it might still be good to have another exporter as an option for debugging in the future. If we *do* want it, I can make sure my other edits/updates are pushed before merging this in. What do you think?

**Comment by BeckySharp** [comment]
yes, go ahead and push your edits and we should merge for future usage

**Comment by zupon** [comment]
Actually, it looks like the most recent update was your `print topk` commit, so it should be good to merge! All I did after that was run it on some docs to test it out.

**Comment by BeckySharp** [comment]
@kwalcock I guess my next steps will involve seeing why this can't be built

**Comment by kwalcock** [comment]
You may have the wrong language.  I think it is trim() in Scala.

```
[info] compiling 152 Scala sources to /var/jenkins_home/workspace/eidos_grounding_exporter/target/scala-2.11/classes ...
[error] /var/jenkins_home/workspace/eidos_grounding_exporter/src/main/scala/org/clulab/wm/eidos/exporters/GroundingInsightExporter.scala:56:71: value strip is not a member of String
[error]         pw.println(s"Sentence $i:\t${doc.sentences(i).getSentenceText.strip()}\n\n")
[error]                                                                       ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

**Comment by BeckySharp** [comment]
hahahaha NICE! yay me!

**Comment by kwalcock** [comment]
Adding an exporter to the collection now...

**Pull request merged**
