### PR TITLE
Make the  mapOntologies method accessible

### PR DESCRIPTION
**Pull request by bsharpataz**
@bgyori  was asking for access to this method to be called chez lui.  I think the re-factoring allows this, but Ben, please check before you approve the PR...?

### CODE REVIEW

**Comment by kwalcock** [comment]
@bsharpataz, rather than
```scala
      val lines = source.getLines().toArray
```
can you try
```scala
      val lines = source.getLines()
      val result: Iterator[ConceptEmbedding] = for {
      ...
      }
      result.toSeq()
```
The debugger thinks the problem is indeed with delayed evaluation caused by the iterator (which even survives the for loop), but I think that toSeq() (or vector or array) afterwards will prevent the entire file from needing to be read at once.  (I haven't managed to get the environment set up to call this myself.)

**Comment by bsharpataz** [comment]
I can try later this afternoon, yes :)

**Comment by kwalcock** [comment]
See also #520 that you can take credit for.

**Comment by kwalcock** [comment]
@bsharpataz any luck on using result.toSeq rather than getLines.toArray?

**Comment by bgyori** [comment]
In the comment above I attempted to fix the issue of getting a string with \n between every character. But I think I must have done something wrong because now I'm getting at "head of empty list" exception and know too little about Scala to solve it. Sorry...

**Comment by bsharpataz** [comment]
Sorry, i totally forgot to do this! Will do now

**Comment by bsharpataz** [comment]
> @bsharpataz any luck on using result.toSeq rather than getLines.toArray?

I spoke with @marcovzla and he told me that Seq is a trait, so it will try to map it to the closest type of Seq to what it is, giving me a Stream.  So, I can choose List, Array, etc, Array seems fine.  But I will try to wait to the end to not load the whole line at once

**Comment by bsharpataz** [comment]
> > @bsharpataz any luck on using result.toSeq rather than getLines.toArray?
> 
> I spoke with @marcovzla and he told me that Seq is a trait, so it will try to map it to the closest type of Seq to what it is, giving me a Stream. So, I can choose List, Array, etc, Array seems fine. But I will try to wait to the end to not load the whole line at once

so -- nope.  Seems the autoclose doesn't like me converting after the scope... you're welcome to play

**Comment by kwalcock** [comment]
Becky is right, of course.  `"this\nis\na\ntest".lines.map { _.toUpperCase }.toSeq` doesn't work, but `"this\nis\na\ntest".lines.map { _.toUpperCase }.toArray` does.  It's probably better than `"this\nis\na\ntest".lines.toArray.map { _.toUpperCase }` because this one will need room for two arrays, the lines and the uppercase lines.  So, I'm hoping that the toArray can be moved to as late as possible within the block.  (Not that it's a super big deal.)

**Comment by bgyori** [comment]
Looks like I misplaced my conf file but once I reinstated it, it works - thanks for the tip @bsharpataz ! I pushed another commit to rename the IDs used for each ontology in the mapping file. This is good to go as far as I'm concerned.

**Comment by kwalcock** [comment]
Sorry, @bsharpataz, but there were merge conflicts with the refactored version in master.  I probably resolved them wrong, but you will be able to fix it in an instant if so.  Search for `// Version from master` and that might be code that should replace what's there now from this branch.

**Comment by bsharpataz** [comment]
sorry @kwalcock I don't know what you mean, sorry to be dense!

**Comment by kwalcock** [comment]
Can you check OntologyMapper.scala in this branch?  The parts that are likely merged wrong are commented.

**Comment by bsharpataz** [comment]
ok, yeah, now I see them, ok I'll fix and push... forthcoming

**Comment by bsharpataz** [comment]
please check me @kwalcock !

**Comment by kwalcock** [comment]
You're checked.  It was just unclear to me whether Ben's version was the latest and greatest or not completely.  This compiles and runs fine.  Thanks.

**Pull request merged**
