### PR TITLE
Prime the Webapp

### PR DESCRIPTION
**Pull request by kwalcock**
This should prepare the webapp to give a quick answer when it is finally initialized and primed.  Docker installation is changed to run the webapp in production mode.

### CODE REVIEW

**Comment by kwalcock** [comment]
There would also temporarily need to be a line in DockerfileProd
```
RUN git checkout kwalcock-webappPriming
```
to test this specific branch.

**Comment by kwalcock** [comment]
It seems to work in docker.  I'll wait a couple of days to hear otherwise from anyone else before merging.

**Comment by BeckySharp** [comment]
does the "production" mode vs "dev" mode make it so that changes to the source code are not seen live, i.e. the webapp would have to be reloaded?

**Comment by kwalcock** [comment]
We can still use webapp/run during development.  The difference is in the preparation of the docker container which uses webapp/stage.  So, yes.  The priming code does run in both cases, so there isn't an extra wait for a response to the first query if you have waited long enough for the priming.  It delays the appearance of the blank form, so checking that is slower.

**Comment by kwalcock** [comment]
So there are now three docker files:
* DockerfileRun - the old Dockerfile that uses "sbt run" as before.  The image builds faster but is slower to run.
* DockerfileRunProd - one that uses "sbt runProd" which is however much slower to start and should be avoided.
* DockerfileStage - one that doesn't use sbt at runtime and doesn't need compilation, etc., and is much faster once it is built

The last one is what should be used in production.

**Comment by kwalcock** [comment]
This addresses #639.

**Pull request merged**
