### PR TITLE
[DART-1003] -  Refactoring how variables are set via environment and config file

### PR DESCRIPTION
**Pull request by yanzv**

### CODE REVIEW

**Comment by kwalcock** [comment]
Thanks for the update.  There are plain Apps for the old way of doing things and LoopApps for doing them automatically.

**Comment by kwalcock** [comment]
Have the changes been verified to work on a "Friday"?

**Comment by yanzv** [comment]
I am working on building docker container and will be able to test it in DART environment.  Let me test it first before merging this PR.

**Comment by kwalcock** [comment]
GitHub wanted several things done on the command line which resulted in #1013 which was then merged.  This PR will probably disappear one way or the other.

**Pull request merged**
