### PR TITLE
Read metal model from resource for NER

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
@vikas95, this PR code results in the error below.  It seems that the new file MetalLocNER.x2i (also called 
Small_size_model_All_loc_data_combined_default_params-epoch7.x2i) is not a substitute for the previous mtl-Kaggle_CoNLL-ner-epoch20.x2i.  Perhaps there is some versioning issue.

```
Exception in thread "main" java.lang.RuntimeException: ERROR: expecting field name intermediateCount; instead I am seeing this line: [# positionWindowSize]!
	at org.clulab.dynet.Utils$ByLineBuilder.addLines(Utils.scala:562)
	at org.clulab.dynet.Utils$ByLineIntBuilder.build(Utils.scala:712)
	at org.clulab.dynet.Utils$ByLineIntBuilder.build(Utils.scala:701)
	at org.clulab.dynet.Utils$ByLineBuilder.build(Utils.scala:600)
	at org.clulab.dynet.Layers$.loadX2i(Layers.scala:183)
	at org.clulab.dynet.Metal$.$anonfun$load$2(Metal.scala:481)
	at org.clulab.dynet.Metal$.$anonfun$load$2$adapted(Metal.scala:480)
	at scala.collection.immutable.Range.foreach(Range.scala:156)
	at org.clulab.dynet.Metal$.$anonfun$load$1(Metal.scala:480)
	at org.clulab.utils.Serializer$.using(Serializer.scala:12)
	at org.clulab.dynet.Metal$.load(Metal.scala:475)
	at org.clulab.dynet.Metal$.apply(Metal.scala:507)
	at org.clulab.wm.eidos.context.GeoNormFinder$.fromConfig(GeoNormFinder.scala:74)
	at org.clulab.wm.eidos.extraction.Finder$.$anonfun$fromConfig$1(Finder.scala:22)
	at scala.collection.immutable.List.map(List.scala:287)
	at org.clulab.wm.eidos.extraction.Finder$.fromConfig(Finder.scala:18)
	at org.clulab.wm.eidos.EidosComponentsBuilder.$anonfun$add$8(EidosComponents.scala:152)
	at org.clulab.wm.eidos.ComponentLoader.load(EidosComponents.scala:54)
	at org.clulab.wm.eidos.EidosComponentsBuilder.$anonfun$loadComponents$3(EidosComponents.scala:78)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.clulab.wm.eidos.utils.Timer$.time(Timer.scala:77)
	at org.clulab.wm.eidos.EidosComponentsBuilder.$anonfun$loadComponents$2(EidosComponents.scala:78)
	at org.clulab.wm.eidos.EidosComponentsBuilder.$anonfun$loadComponents$2$adapted(EidosComponents.scala:76)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:156)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by kwalcock** [comment]
Again can @vikas95 or maybe @MihaiSurdeanu look at this?  I think that the solution is dependent on the history of the code.

**Comment by MihaiSurdeanu** [comment]
1. This bug is caused by some recent changes I made in the model file format. Let's discuss at the WM meeting today. @vikas95: you will have to retrain the model. But wait until we discuss.
2. Why is the SeqScorer copied here from processors, instead of just importing the SeqScorer from processors? @vikas95: please fix this.

**Comment by kwalcock** [comment]
This has been incorporated into the dynetgeonorm branch.

**Pull request closed without merging**
