### PR TITLE
Fix collecting of EidosMentions

### PR DESCRIPTION
**Pull request by kwalcock**
Adjust grounding name

### CODE REVIEW

**Comment by kwalcock** [comment]
@zupon, here's an update for string tests.  Let me know how close or far that is from what you need.

**Comment by kwalcock** [comment]
@zupon, @BeckySharp, to ground against simple text, I avoided some things in EidosOntologyGrounder.groundOntology because they involve use of the mention type.  I can add that as a parameter that can be passed in along with the text, though.  I do see that patterns are matched against odinMention.text while wordToVec gets run on the canonicalNameParts.  This was one of my concerns with regrounding.  If Ben calls it without a proper mention, it will probably not get the same result if it was a pattern that matched when grounded previously.

**Comment by BeckySharp** [comment]
OK, makes sense, I wonder if we need to receive both when he calls
"reground".... or we can parse on the fly and repeat the canonicalization?

**Comment by zupon** [comment]
I added some stuff to `groundStrings` in `EidosOntologyGrounder` so that we can match the regex patterns for the `property` branch without needing to invoke any kinds of mentions. I also changed around some of how I was checking the strings, and things seem to be working better. @BeckySharp  we can look at it when we meet tomorrow (12/5) and @kwalcock I'll keep you posted on what's going on.

**Comment by kwalcock** [comment]
Cool.  I was going to do something like that five minutes from now.  Instead, I'll wait and see what you came up with.

**Comment by BeckySharp** [comment]
sounds great!

**Comment by kwalcock** [comment]
IIRC canonicalization requires things like POS which won't be available either.
```
 def isCanonical(lemma: String, tag: String, ner: String)
```

**Comment by BeckySharp** [comment]
true, though we could parse them again, or at least POS tag them with
processors....

**Comment by kwalcock** [comment]
Wouldn't we need the entire sentence then?  That may not be in the mention text or canonicalName.

**Comment by BeckySharp** [comment]
I think for POS tagging/NER/lemmatization we'd do decent with just the
mention text, but I can try to check empirically if you want

**Pull request merged**
