### PR TITLE
Geonormalization included

### PR DESCRIPTION
**Pull request by vikas95**
This pull request is for the GeoNorm branch which adds geonorm (location phrases, geoname IDs, start and end offset, attachements) to the previous Eidos version (till TimeNorm).

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@kwalcock: can you please review this?

**Comment by kwalcock** [comment]
Please have mercy on us people with bifocals and short memories.  Can you distinguish these variables better?  If a comment is required, it may as well be incorporated into the name.

jldTAttachments
jldLAttachments
jldDAttachments

**Comment by vikas95** [comment]
@EgoLaparra - I am removing all the comments (sorry, I forgot, you had suggested this a week ago).

@kwalcock - I apologize for the minute variations in the variable names, I was trying to replicate exactly what Egoitz had done for time normalization and most of the location variables would be very similar to time variables except name would indicate location instead of time. I'll try to rename few variables such that it becomes more clear for the reviewer.

Thanks.

**Comment by kwalcock** [comment]
@vikas95, don't worry too much.  Your code is pretty good, especially for a first (or second or third) PR.

There are exceptions being thrown on my computer, so chances are that some change is necessary.  In the meantime, is the commented line of code some workaround to achieve the same thing as the line after it?

  private def readDict_label(dictFile: InputStream): collection.mutable.Map[Double, String] = {
  //  var Idx2label =  collection.mutable.Map(100.toDouble -> "dummy") // initializing the word2idx
    var Idx2label =  collection.mutable.Map.empty[Double, String] // initializing the word2idx

**Comment by kwalcock** [comment]
There is a problem with how the the files context/*.txt are being opened.  They're not guaranteed to be using UTF-8 in Java.  (It is somewhat dependent on environment.)  There are some utility functions to handle this.  Rather than trying to explain it and then going through several rounds of back and forth, I propose to submit a PR on your branch and ask you to check it over carefully.  I will no doubt have added problems of my own doing.

**Comment by kwalcock** [comment]
Nevermind about `collection.mutable.Map.empty[Double, String]`.  That function is never called.  It doesn't look like the file index2label_geonorm.txt is ever used, either.

**Comment by kwalcock** [comment]
There is going to be a problem with tokenization.  Eidos already tokenizes.  For the sentence

```
The Food and Agriculture Organization of the United Nations (FAO), the United Nations Children's Fund (UNICEF) and the World Food Programme (WFP) stressed that while the deteriorating situation coincides with an unusually long and harsh annual lean season, when families have depleted their food stocks and new harvests are not expected until August, the level of food insecurity this year is unprecedented.
```

Eidos finds 73 tokens.  create_word_input(sourceText: String) results in only 43 when called in EidosDocument:

```
val token_labels = geo_disambiguate.generate_NER_labels(geo_disambiguate.create_word_input(this.sentences(index).getSentenceText)._1)
```
This eventually results in an exception because the two sizes are expected to be the same.  Something will have to change here.  Can you give it some thought?

**Comment by kwalcock** [comment]
The choice seems to be between sentence.raw and sentence.word.  It might depend on which were used in training.  I'm favoring raw, but someone else may know better.

**Comment by kwalcock** [comment]
@vikas95, in generate_NER_labels, with N words, should the size of label_predictions also be N?  It looks like 20 words are going in and 21 labels are coming out.

**Comment by kwalcock** [comment]
In case someone like @EgoLaparra might also know,  I see in some cases 20 word_features going in and 24 label_predictions, which eventually leads to the program crashing.

```scala
  def generate_NER_labels(word_features: ListBuffer[Float]): ListBuffer[String] = {

    val word_input = Nd4j.create(word_features.toArray)
    this.network.setInput(0, word_input)
    val results = this.network.feedForward()

    val output = results.get("time_distributed_1")
    val label_predictions = output.shape()(0) match {
      case 1 => Array(results.get("time_distributed_1").toFloatVector())
      case _ => results.get("time_distributed_1").toFloatMatrix()
    }

    var predicted_labels = new ListBuffer[String]
    for (word1_label <- label_predictions) {

      predicted_labels += int2label(word1_label.zipWithIndex.maxBy(_._1)._2)
    }

     return predicted_labels
  }
```

**Comment by vikas95** [comment]
@kwalcock and @EgoLaparra , can this happen because of different tokenization ?? 
I am removing my tokenizations and using the tokens from Eidos (instead of sentence). I feel this should solve the mismatch ??

**Comment by kwalcock** [comment]
I don't think it is a tokenization problem.  The Geo_disambiguate_parser is no longer parsing any text.  Here's the current code below.  Don't change much until I do a PR on your branch.
```scala
  def createFeatures(words: Array[String]): Array[Float] = {
    val unknown = word2int(Geo_disambiguate_parser.UNKNOWN_TOKEN)
    val features = words.map(word2int.getOrElse(_, unknown).toFloat)

    features
  }
```

**Comment by kwalcock** [comment]
Please see #497 for proposed updates to this code.

**Comment by kwalcock** [comment]
Just for clarity, this code doesn't seem to be working, where this code is waiting to be merged into this branch in #497.

```scala
  def generateLabels(word_features: Array[Float]): Array[String] = {
    val word_input = Nd4j.create(word_features.toArray)
    network.setInput(0, word_input)

    val results = network.feedForward()
    val output = results.get(Geo_disambiguate_parser.TIME_DISTRIBUTED_1)
    val label_predictions: Array[Array[Float]] = output.shape()(0) match {
      case 1 => Array(output.toFloatVector())
      case _ => output.toFloatMatrix()
    }

    // TODO: Why does this happen?
    if (label_predictions.size != word_features.size)
      println("Not working")
    else
      println("Working fine")
    label_predictions.map { word1_label =>
      Geo_disambiguate_parser.INT2LABEL(word1_label.zipWithIndex.maxBy(_._1)._2)
    }
  }
```

**Comment by kwalcock** [comment]
The problem seems to be that this code isn't thread safe :(  However, there is probably an easy solution for that :)

**Comment by EgoLaparra** [comment]
Geo_disambiguate_parser uses mutable objects like ListBuffer. Could this be the cause?

**Comment by vikas95** [comment]
> Just for clarity, this code doesn't seem to be working, where this code is waiting to be merged into this branch in #497.
> 
> ```scala
>   def generateLabels(word_features: Array[Float]): Array[String] = {
>     val word_input = Nd4j.create(word_features.toArray)
>     network.setInput(0, word_input)
> 
>     val results = network.feedForward()
>     val output = results.get(Geo_disambiguate_parser.TIME_DISTRIBUTED_1)
>     val label_predictions: Array[Array[Float]] = output.shape()(0) match {
>       case 1 => Array(output.toFloatVector())
>       case _ => output.toFloatMatrix()
>     }
> 
>     // TODO: Why does this happen?
>     if (label_predictions.size != word_features.size)
>       println("Not working")
>     else
>       println("Working fine")
>     label_predictions.map { word1_label =>
>       Geo_disambiguate_parser.INT2LABEL(word1_label.zipWithIndex.maxBy(_._1)._2)
>     }
>   }
> ```

@kwalcock, thanks for making all the changes, I tried merging kwalcock-geoNorm1 into geoNorm from your pull request but there is some conflict in HomeController.scala file. 
Can you share an example sentence which shows more number out outputs as compared to number of tokens. By looking at the sentence, I can be sure that the mistake is in tokenization. 
Thanks again for the changes.

**Comment by vikas95** [comment]
> Some other branch seems to have messed something up with HomeController.scala. I'll try to merge it myself if nobody objects.

@kwalcock - Sorry if it was because of this - I commented out 2 lines in HomeController.scala which was given as suggestions because of the conflict. That is the only change I had made 30 mins ago. The suggested changes were looking fine to me but they are still in the HomeController.scala file (I just commented them out)

**Comment by kwalcock** [comment]
@vikas95, in makeLocationPhrases (or whatever it is now called), there will be no GeoPhraseID produced if the sentence ends on a B-LOC or I-LOC.  A GeoPhraseID will be produced for "I live in Tucson now" but not for "I live in Tucson".  I'll be presumptuous and add a line to change if you check the work after the merge.

**Comment by kwalcock** [comment]
There is sample output with geolocations (not time or grounding) at https://drive.google.com/open?id=1CtAB0q9_Qbx82ckPX2wGlbZYgb9yNHCq.  I'll merge in the morning.

**Comment by vikas95** [comment]
> @vikas95, in makeLocationPhrases (or whatever it is now called), there will be no GeoPhraseID produced if the sentence ends on a B-LOC or I-LOC. A GeoPhraseID will be produced for "I live in Tucson now" but not for "I live in Tucson". I'll be presumptuous and add a line to change if you check the work after the merge.

@kwalcock - Yes, you are correct, I was missing this before. 
Thanks for adding it.

**Comment by kwalcock** [comment]
Thanks for the reminder.  I learned about webapp/test yesterday!  "Found GeoLocations" has been added to the webapp and someone contributed a web service.  See the readme for exciting details.  It *seems* to be working.

**Comment by kwalcock** [comment]
Here's the current quandary:

```
Most came because of the ongoing fighting in South Kordofan and Blue Nile states in Sudan and settled predominantly in 21 refugee locations in Unity and Upper Nile.
```
results in

```
List(Concept, Entity) => ongoing fighting in South Kordofan and Blue Nile states in Sudan and settled predominantly in 21 refugee locations in Unity and Upper Nile 
     ------------------------------ 
     Rule => gradable-lexiconner++simple-np++quantification2++simple-vp 
     Type => TextBoundMention 
     ------------------------------ 
     Concept, Entity => ongoing fighting in South Kordofan and Blue Nile states in Sudan and settled predominantly in 21 refugee locations in Unity and Upper Nile 
     * Attachments: Location(Unity), Quantification(ongoing,None), Location(Unity), Location(Unity), Location(Sudan) 
     ------------------------------ 
```
with **3** `Location(Unity)`.

**Comment by kwalcock** [comment]
It would be helpful to add the actual text here:
```
Found GeoLocations:
     span: 45,50 
     geoNameID: Some(2395504)
```

**Comment by bsharpataz** [comment]
> Here's the current quandary:
> 
> ```
> Most came because of the ongoing fighting in South Kordofan and Blue Nile states in Sudan and settled predominantly in 21 refugee locations in Unity and Upper Nile.
> ```
> results in
> 
> ```
> List(Concept, Entity) => ongoing fighting in South Kordofan and Blue Nile states in Sudan and settled predominantly in 21 refugee locations in Unity and Upper Nile 
>      ------------------------------ 
>      Rule => gradable-lexiconner++simple-np++quantification2++simple-vp 
>      Type => TextBoundMention 
>      ------------------------------ 
>      Concept, Entity => ongoing fighting in South Kordofan and Blue Nile states in Sudan and settled predominantly in 21 refugee locations in Unity and Upper Nile 
>      * Attachments: Location(Unity), Quantification(ongoing,None), Location(Unity), Location(Unity), Location(Sudan) 
>      ------------------------------ 
> ```
> with **3** `Location(Unity)`.

@vikas95 and @kwalcock -- I suspect that the location is attached to several concepts, and then during expansion we grab them all happily.  this can be verified by temporarily disabling expansion in the global action and seeing.  If this is the case, then perhaps one of you can add a filter to make sure that we do essentially a `.distinct` operation on the attachments....? 

if that ends up happening, @kwalcock you should prob not merge #500 until I port the change over? or we can merge that first if this PR seems a ways away?

**Comment by kwalcock** [comment]
I think the problem is that the ContextAttachments have provided no equality override (or ordering).  They are thrown into a Set, but don't realize that they're duplicates.

**Comment by kwalcock** [comment]
That does seem to be the problem, although perhaps not the only one.  I'm working on it.

**Pull request merged**
