### PR TITLE
Add context to context for JSON-LD

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Thanks!

Does that make our output loadable in jsonld-java?

**Comment by kwalcock** [comment]
@adarshp, are you reading in JSON-LD for your visualization?  Will this change mess you up?  The output now begins with
{
  "@context" : {
    "@context" : {
      "@base" : "https://github.com/clulab/eidos/wiki/JSON-LD"
    },
    "Corpus" : "#Corpus",

rather than just

{
  "@context" : {
    "@base" : "https://github.com/clulab/eidos/wiki/JSON-LD"
    "Corpus" : "#Corpus",

**Comment by kwalcock** [comment]
The Wiki page has been updated for this syntax and the example can be copied and pasted into https://json-ld.org/playground/ without it complaining.

**Comment by adarshp** [comment]
I do read in JSON-LD - I'm not sure whether this would mess anything up, but I am fairly sure that it's an easy modification to make. I'm tagging @bgyori to let him know of the updated format.

**Comment by kwalcock** [comment]
It loads without complaint.  @MihaiSurdeanu, we were recently discussing possible modifications to this format and I was about to get back to you on that.

**Comment by MihaiSurdeanu** [comment]
Yes, please. Thanks!!

**Comment by kwalcock** [comment]
https://github.com/jsonld-java doesn't like it.  Please stand by.

**Comment by kwalcock** [comment]
The format changed again for the sake of jsonld-java.  The @base has been abandoned and the file now starts as below.  Ironically, at some point in the development process it had looked like this already.

{
  "@context" : {
    "Corpus" : "https://github.com/clulab/eidos/wiki/JSON-LD#Corpus",
    "Dependency" : "https://github.com/clulab/eidos/wiki/JSON-LD#Dependency",
    "DirectedRelation" : "https://github.com/clulab/eidos/wiki/JSON-LD#DirectedRelation",
    "Document" : "https://github.com/clulab/eidos/wiki/JSON-LD#Document",
    "Entity" : "https://github.com/clulab/eidos/wiki/JSON-LD#Entity",
    "Interval" : "https://github.com/clulab/eidos/wiki/JSON-LD#Interval",
    "Provenance" : "https://github.com/clulab/eidos/wiki/JSON-LD#Provenance",
    "Sentence" : "https://github.com/clulab/eidos/wiki/JSON-LD#Sentence",
    "State" : "https://github.com/clulab/eidos/wiki/JSON-LD#State",
    "Trigger" : "https://github.com/clulab/eidos/wiki/JSON-LD#Trigger",
    "Word" : "https://github.com/clulab/eidos/wiki/JSON-LD#Word"
  },

**Comment by kwalcock** [comment]
It can be merged as far as I'm concerned.

**Comment by MihaiSurdeanu** [comment]
@bsharpataz: can you please generate the output on the 10 docs with this version of eidos? And post it on the sharepoint?

**Comment by bsharpataz** [comment]
yes -- and I should say that it's jsonld-java?

**Comment by kwalcock** [comment]
So that's just a java library that can read the file and it was rudimentarily tested.  The format isn't especially changed.  Maybe it went from JSON-LD 1.1 back to 1.0 or something.  So not "it is" jsonld-java but maybe "works with".  Had you already done this once yesterday?  Sorry.

**Comment by bsharpataz** [comment]
no -- doing now

**Pull request merged**
