### PR TITLE
Modified ExtractFromDirectory app to process files in parallel (taking advantage of multiple CPU cores)

### PR DESCRIPTION
**Pull request by adarshp**

### CODE REVIEW

**Comment by kwalcock** [comment]
Do you know offhand whether

println(s"Extracting from ${file.getName}")

is thread safe?  Will the output be intermixed?

**Comment by kwalcock** [comment]
Looks like it is documented as synchronized, so disregard.

**Comment by kwalcock** [comment]
@ajaynagesh, you were making a similar change.  Does this work well with what you have?

**Comment by ajaynagesh** [comment]
@kwalcock I noticed that if all the threads write to the same file on disk, the parallelization is very slow due to locks for write being shared. Better to write to separate files. At least this is what I observed in my case.

**Comment by kwalcock** [comment]
Thanks.  I think this one has a separate output file for every input file.

**Comment by kwalcock** [comment]
Somewhere in EidosSystem there is an ordering dependency.  If multiple texts are fed into the system, the result will be dependent on their ordering.  The parallel version can result in a different order of files and it can get a different answer on two runs.  Some kind of state is being preserved.

**Comment by bsharpataz** [comment]
the result of "canonicalName" ?

**Comment by kwalcock** [comment]
The difference is
        "entity" : "O",
versus
        "entity" : "LOCATION",

One version
      }, {
        "@type" : "Word",
        "@id" : "_:Word_378",
        "tag" : "NNP",
        "entity" : "O",
        "startOffset" : 496,
        "endOffset" : 501,
        "lemma" : "Green",
        "chunk" : "I-NP"
      }, {
        "@type" : "Word",
        "@id" : "_:Word_379",
        "tag" : "NNP",
        "entity" : "O",
        "startOffset" : 502,
        "endOffset" : 506,
        "lemma" : "Belt",
        "chunk" : "I-NP"
      }, {

Other version

      }, {
        "@type" : "Word",
        "@id" : "_:Word_378",
        "tag" : "NNP",
        "entity" : "LOCATION",
        "startOffset" : 496,
        "endOffset" : 501,
        "lemma" : "Green",
        "chunk" : "I-NP"
      }, {
        "@type" : "Word",
        "@id" : "_:Word_379",
        "tag" : "NNP",
        "entity" : "LOCATION",
        "startOffset" : 502,
        "endOffset" : 506,
        "lemma" : "Belt",
        "chunk" : "I-NP"
      }, {

**Comment by kwalcock** [comment]
There is test code on a different branch that attempts to isolate the problem, not very successfully.  The problem isn't with ExtractFromDirectory itself.  So, I'm going to check this in.  These notes are hopefully sufficient paper trail.

**Comment by ajaynagesh** [comment]
@MihaiSurdeanu : Is the output of the histograms due to the effect mentioned in this thread ?

**Comment by kwalcock** [comment]
Did you get some strange results?

**Pull request merged**
