### PR TITLE
maria's comments on entities vs. events.. preceeded with Maria:

### PR DESCRIPTION
**Pull request by ajaynagesh**
Placeholder for discussion of a broader question of when some ontology nodes should be treated as entities or events (processes etc.). The definition is not clear yet either to me or Maria Stroica ...

### CODE REVIEW

**Comment by ajaynagesh** [comment]
Further discussions ...
 
Top-level nodes according to Maria
--------------
- Property (characteristics of an entity/event … which cannot be very easily quantified .. e.g.: aridity, ability, availability)
- Event (entities undergoing processes, e.g.: deforestation, snowfall, rainfall)
- Entity ( anything that has an attribute or a property .. and typically static)
- Units
- Attribute (characteristics of a system property value pair, e.g.: arable_land=%_of_land)
- Operator (ratio / percentage … )

Phenomenon (e.g: gravity) vs Event (hurricane Katrina ...)

**Comment by kwalcock** [comment]
It should be easy enough to run a spell checker over our ontologies.  Let's make that part of the process.
These are just in the comments, but other mistakes haven't been.
occuring -> occurring
govenrment -> government

**Comment by ajaynagesh** [comment]
@kwalcock sure ... 

Here is a subset of variables which Maria gave me from the GSN ontology that are relevant and could be added to augment our un_ontology: 

https://docs.google.com/spreadsheets/d/1gGPJiyXtE-70Af0Kh7bu6svc7GbIrP-qdoKWuaOnQ_k/edit#gid=1770194572

**Comment by kwalcock** [comment]
Both spellings of anemia/anaemia were present, so there was really no need to choose.

**Comment by ajaynagesh** [comment]
I noticed that this PR was merged. Just wanted to point out, some of the comments (for instance reorganization of some of nodes as entities or events) need more thought and discussion, before incorporating those comments.

**Comment by bsharpataz** [comment]
if this is a good place to mention this -- the reorganization or top-level
branches (i.e., units, etc) should be thought through in terms of how we
will ground to things/represent groundings before we implement in the
ontology

**Pull request merged**
