### PR TITLE
Linking migrations

### PR DESCRIPTION
**Pull request by zupon**
@MihaiSurdeanu 
We rewrote the method to combine event fragments. It works on the examples we tested.
Here are some sentences to try it out:
- `Arrivals: 358 individuals came from Uganda citing Juba as intended destination`
- `300 refugees fled South Sudan. Their destination is Ethiopia.`
- `Interviewed KIs passed through Nimule and Juba before settling in Bor.`

### CODE REVIEW

**Comment by kwalcock** [comment]
I hope that nobody is waiting for me on this.  I generally just watch the merges into master and let the inter-branch PRs be worked out between owners of the two branches.

**Comment by kwalcock** [comment]
The reason I looked at all is because the Jenkins build seems to have hung.  That I am working on.

**Comment by maxaalexeeva** [comment]
@kwalcock, thank you for checking! Still working on this branch/not waiting for you on this.

**Comment by maxaalexeeva** [comment]
@zupon, FYI, running this ```300 refugees fled South Sudan. They left the country to go to Ethiopia. ``` (an example I made up to work on overlapping args) results in this error:

```[error] application - 

! @7c8e6m5m5 - Internal server error, for (GET) [/parseText?text=300+refugees+fled+South+Sudan.+They+left+the+country+to+go+to+Ethiopia.+&cagRelevantOnly=false] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ArrayIndexOutOfBoundsException: 7]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
        at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:251)
        at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:250)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 7
        at org.clulab.odin.Mention.endOffset(Mention.scala:76)
        at org.clulab.odin.Mention.endOffset$(Mention.scala:76)
        at org.clulab.odin.EventMention.endOffset(Mention.scala:240)
        at org.clulab.odin.Mention.text(Mention.scala:140)
        at org.clulab.odin.Mention.text$(Mention.scala:139)
        at org.clulab.odin.EventMention.text(Mention.scala:240)
        at org.clulab.wm.eidos.utils.DisplayUtils$.mentionToDisplayString(DisplayUtils.scala:92)
        at org.clulab.wm.eidos.utils.DisplayUtils$.displayMention(DisplayUtils.scala:151)
        at controllers.HomeController.$anonfun$mkJson$1(HomeController.scala:275)
        at controllers.HomeController.$anonfun$mkJson$1$adapted(HomeController.scala:275)
```

I haven't figured the error out yet.

**Comment by BeckySharp** [comment]
OOh I may be able to help -- Are you using CrossSentenceMentions for those?

**Comment by maxaalexeeva** [comment]
@zupon, @BeckySharp helped me figure out the error. I will start working on a fix now.

**Comment by maxaalexeeva** [comment]
@MihaiSurdeanu,

The event for merging seems to be working. The main method is here, and there are several support methods for it, too:

https://github.com/clulab/eidos/blob/5171f139ceba72d0d8267878b3570a632b5b50a2/src/main/scala/org/clulab/wm/eidos/actions/MigrationUtils.scala#L132

The looping seems to work and is here:

https://github.com/clulab/eidos/blob/5171f139ceba72d0d8267878b3570a632b5b50a2/src/main/scala/org/clulab/wm/eidos/actions/MigrationUtils.scala#L199

There is functionality to choose the more specific mention out of the two being compared, but it does not work for the example below (`country` is not resolved to `South Sudan`) bc there is a constraint on merging events if they both contain specific information with the same argName (in this case, the number of people):

Screenshot from 2019-06-26 22-57-16

Should I try to make a corefMention for cases like this? E.g., if there's a non-specific location (with no attachments), resolve it to the previous specific one? 

There are a few things that make it impossible to merge this whole thing into master yet, but it should be safe to merge it into migration_schema-zupon. I'd like to close this pull request to see how the methods here interact with the normalization code you wrote. The errors in jenkins come from the main migration event branch as far as I remember. 

Some current issues:

- I talked to Steven today, and there will be some changes in the next week or two to how locations are handled, so the fragment merging methods might need to be updated;
- there will be changes to how times are handled, so I decided against writing methods to normalize time now to avoid having to rewrite them when the changes have happened. Steven said he will let me know when the changes have been merged and we can meet again; there are a few stubs for time methods that I would like to keep in the file for now if that's ok. 
- Steve and I (and later Becky and I) also discussed the possibility of using a gazetteer for locations.

**Comment by MihaiSurdeanu** [comment]
@maxaalexeeva: this looks pretty good!

- `returnedEvents` should be an ArrayBuffer rather than an Array. Using an Array, creates a new Array every time you add to it, which is inefficient. The ArrayBuffer lets you append to the same dynamic array (using `+=`) wo/ creating a new one. Just convert it to Array in the last line of the method, using `returnedEvents.toArray`.

- Yes, it would be great to add some basic location coref, say from a small list of common nouns (e.g., "country") to the closest compatible location to the left.

- I think the `intersect` calls in `isMergeable` will have to be changed to something more semantic later on, to allow for equivalent args that are slightly different lexically. But for now, this is great!

**Comment by maxaalexeeva** [comment]
Thanks for the feedback! Will address the comments soon and will check in
again before merging.

**Comment by maxaalexeeva** [comment]
@MihaiSurdeanu, 

I changed Array to ArrayBuffer. `returnedEvents.toArray` was giving me an error, but just returning `returnedEvents` seems to work. 

Here is a version of a method for resolving non-specific locations:
https://github.com/clulab/eidos/blob/3e7730c99e060fe763c3aa50437461c446ae2c1e/src/main/scala/org/clulab/wm/eidos/actions/MigrationUtils.scala#L327

Here are the generic location word list with the words coming from the lexicon @zupon put together based on our examples; I am not sure all of them will need to be resolved, so the list is to be discussed:
https://github.com/clulab/eidos/blob/3e7730c99e060fe763c3aa50437461c446ae2c1e/src/main/scala/org/clulab/wm/eidos/actions/MigrationUtils.scala#L430

**Comment by MihaiSurdeanu** [comment]
Looks great!

**Pull request merged**
