### PR TITLE
added relation mentions to webapp display

### PR DESCRIPTION
**Pull request by bsharpataz**
added relation mentions to webapp display

### CODE REVIEW

**Comment by kwalcock** [comment]
Do you have a simple sentence I can test with?

**Comment by kwalcock** [comment]
@bsharpataz, can you check this code?  In the top one I see `e.arguments.values` and in the bottom `e.arguments.values.flatten`.  I don't think the top one will ever satisfy `if a.isInstanceOf[EventMention]` because e.arguments.values will be an Iterable[Seq[Mention]] and a will be Seq[Mention].  Is there a sentence that can be used to test this?  The code is probably never used in an important place.

```
    // collect triggers for event mentions
    val triggers = events.flatMap { e =>
      val argTriggers = for {
        a <- e.arguments.values
        if a.isInstanceOf[EventMention]
      } yield a.asInstanceOf[EventMention].trigger
      e.trigger +: argTriggers.toSeq
    }
    // collect event arguments as text bound mentions
    val entities = for {
      e <- events ++ relations
      a <- e.arguments.values.flatten
    } yield a match {
      case m: TextBoundMention => m
      case m: RelationMention => new TextBoundMention(m.labels, m.tokenInterval, m.sentence, m.document, m.keep, m.foundBy)
      case m: EventMention => m.trigger
    }
```

**Comment by kwalcock** [comment]
In a local version I've gone and replaced things like this
```
    val topLevelTBM = mentions.flatMap {
      case m: TextBoundMention => Some(m)
      case _ => None
    }
```
with this
```
    val topLevelTBM = mentions.collect { case m: TextBoundMention => m }
```
Apparently that's the Scala way and it's probably more efficient as well.  I'll merge it after hearing about the issue above.

**Comment by bsharpataz** [comment]
> @bsharpataz, can you check this code? In the top one I see `e.arguments.values` and in the bottom `e.arguments.values.flatten`. I don't think the top one will ever satisfy `if a.isInstanceOf[EventMention]` because e.arguments.values will be an Iterable[Seq[Mention]] and a will be Seq[Mention]. Is there a sentence that can be used to test this? The code is probably never used in an important place.
> 
> ```
>     // collect triggers for event mentions
>     val triggers = events.flatMap { e =>
>       val argTriggers = for {
>         a <- e.arguments.values
>         if a.isInstanceOf[EventMention]
>       } yield a.asInstanceOf[EventMention].trigger
>       e.trigger +: argTriggers.toSeq
>     }
>     // collect event arguments as text bound mentions
>     val entities = for {
>       e <- events ++ relations
>       a <- e.arguments.values.flatten
>     } yield a match {
>       case m: TextBoundMention => m
>       case m: RelationMention => new TextBoundMention(m.labels, m.tokenInterval, m.sentence, m.document, m.keep, m.foundBy)
>       case m: EventMention => m.trigger
>     }
> ```

yeah -- I think you're right.... and i also think you're right that it's a not-very-used part of the code, I think it only hits there if the arg of an EventMention is itself an EventMention, but YEP i but this wouldn't work :)  Care to throw a `.flatten` in there for me? and THANKS for the thorough reviewing!

**Pull request merged**
