### PR TITLE
Canonicalize texts and ontology nodes the same way

### PR DESCRIPTION
**Pull request by kwalcock**
Namely,
```
  protected def isContentTag(tag: String) =
      tag.startsWith("NN") ||
      tag.startsWith("VB")

  def isCanonical(lemma: String, tag: String, ner: String): Boolean =
    isContentTag(tag) &&
    !stopwordManaging.containsStopword(lemma) &&
    !StopwordManager.STOP_NER.contains(ner)
```

Also, not only do descriptions pass through this check, but so do examples and even node names.  Node names are now also added to the values against which the nodes are grounded.  _ characters are replaced with spaces in node names.

The vectors had been converted to Floats, but now so have the outputs of word2vec operations.  This is done to conserve memory, especially since incoming data is at less than float precision.

### CODE REVIEW

**Comment by kwalcock** [comment]
@ajaynagesh, Mihai wanted some kind of evaluation of whether these changes help or hurt performance and claimed that you have a way to evaluate it.  Can you do so?

It might also be good to test whether adding "JJ" to the acceptible parts of speech helps.  It was in the code for the ontologies but not for the document texts.

Also I finally notice that the old code for text used startsWith("NN") while the code for ontologies has contains("NN").  I'm not familiar enough with the tagset to know the repurcussions, so it would be great if @ajaynagesh and @bsharpataz weighed in.  Contains is of course more general.  Thanks.

**Comment by ajaynagesh** [comment]
Certainly @kwalcock! Will let you know about this soon ...

**Comment by kwalcock** [comment]
Also, in un_ontology.yml I notice a lot of `provision of provision of` and wonder if there was some sort of search and replace error.  I'm not sure what that phrase means.

**Comment by kwalcock** [comment]
@ajaynagesh, are this and #435 going OK?

**Comment by bsharpataz** [comment]
> Also, in un_ontology.yml I notice a lot of `provision of provision of` and wonder if there was some sort of search and replace error. I'm not sure what that phrase means.

Sorry -- meant to reply to this sooner.  This comes from the way I converted the sheet from Kimetrica into a format for us.  In general their specs recommend for them to avoid including the "provision of" in the node name, however, for grounding, I was thinking it would be helpful (to ground to the _provision of_ food rather than _food_ itself?), so I inserted it.  However, they didn't always follow their own spec, so sometimes it's duplicated.  This could be fixed, but IDK if it matters in terms of the way it's all used in the grounding algorithm...

**Comment by kwalcock** [comment]
I haven't seen that, but can imagine what is going wrong.  I'm checking.

**Comment by kwalcock** [comment]
Sorry about that.  It should be fixed.

**Comment by ajaynagesh** [comment]
Thanks @kwalcock , It is working currently. I am evaluating both. I have run `ExtractAndExport` on both `master` and `kwalcock-canononical` and evaluating the results. I think there is a slight change in the ontology, so I have regenerate the gold standard grounding for this again. 

I will report the numbers soon. Upon preliminary examination of the grounding outputs, there is little difference between both the versions. In a few cases, the kwalcock-cononical has better groundings compared to the master.

**Comment by ajaynagesh** [comment]
Ok here are the results: 

master: 69.27% 
kwalcock-canonical: 66.67% 

Performance is more or less similar. But the master has a slightly better performance. Also I noticed that with some of the new intervention nodes in the ontology, there seems to be more errors in grounding. This is present in both master and kwalcock-canonical. 

The detailed spreadsheet is present at: https://docs.google.com/spreadsheets/d/1CNb0swt1EBJOX7rD74S39GU0NCUZQvGM2Ky14ZxELLg/edit#gid=0

**Comment by kwalcock** [comment]
Thanks, @ajaynagesh.  I wonder if this means that adjectives should be added back.  The code was once
```
          wordAndPos._2.contains("NN") ||
            wordAndPos._2.contains("JJ") ||
            wordAndPos._2.contains("VB")
```
We've also got code soon to be included that says
```
  def contentWords(ws: Seq[String]): Seq[String] = {
//    def contentTag(s: String): Boolean = {
//      s.startsWith("N") || s.startsWith("V") || s.startsWith("J")
//    }
//
//    val doc = proc.mkDocument(ws.mkString(" "))
//    proc.tagPartsOfSpeech(doc)
//    for {
//      (w, i) <- doc.sentences.head.words.zipWithIndex
//      tag = doc.sentences.head.tags.get(i)
//      if contentTag(tag) && w != "provision"
//    } yield w
    ws//.filter(!_.startsWith("provision"))
  }
```
We have differing parts of speech, either startsWith or contains, and words or lemmas.  It seems like these should all be the same.

**Comment by ajaynagesh** [comment]
Hi @kwalcock , @MihaiSurdeanu : 

Ran with the adjectives included in kwalcock-canonical. Basically, the code is the following now: 

`class Canonicalizer(stopwordManaging: StopwordManaging) {

  protected def isContentTag(tag: String) =
      tag.startsWith("NN") ||
      tag.startsWith("VB") ||
      tag.startsWith("JJ")

  def isCanonical(lemma: String, tag: String, ner: String): Boolean =
    isContentTag(tag) &&
    !stopwordManaging.containsStopword(lemma) &&
    !StopwordManager.STOP_NER.contains(ner)
}`

The results drop a little bit more. So the results now are following: 

`master: 69.27%
kwalcock-canonical: 66.67%
kwalcock-canonical-adj: 64.06%` 

results are updated in https://docs.google.com/spreadsheets/d/1CNb0swt1EBJOX7rD74S39GU0NCUZQvGM2Ky14ZxELLg/edit#gid=0

**Comment by kwalcock** [comment]
Thanks, @ajaynagesh.  Is this with all ontolgies?

**Comment by ajaynagesh** [comment]
It is with un_ontology only. Also I am evaluating with only un_ontology currently.

**Comment by kwalcock** [comment]
Just so people know, the UN ontology has only examples rather than descriptions.  Examples were not being filtered at all previously.  That was reserved for descriptions.  In addition, the name of the leaf node has been added as well as names of all the parents.  I see a field in the ontology that I didn't notice before, keywords.  The program is ignoring those.

**Comment by ajaynagesh** [comment]
I would vote for merging `kwalcock-canonical` as is .. given the results with `adj` bumps down the accuracy a little bit on our small test set ..

**Comment by MihaiSurdeanu** [comment]
@kwalcock: Got it. I think it's Ok to ignore keywords. Can we run one more test: ignore the names of all the parents?

**Comment by kwalcock** [comment]
Well, I wouldn't want to add to Ajay's workload.

The names would need to be commented out of these lines of code in TreeDomainOntology.scala for the test.  Later I can remove some of the unnecessarily calculations.
```
class OntologyLeafNode(nodeName: String, parent: OntologyBranchNode, polarity: Float, names: Seq[String], examples: Option[Seq[String]] = None, descriptions: Option[Seq[String]] = None) extends OntologyNode(nodeName, parent) with Namer {

  def name: String = fullName

  // Right now it doesn't matter where these come from, so they can be combined.
  val values: Array[String] = (/*names ++ */ examples.getOrElse(Seq.empty) ++ descriptions.getOrElse(Seq.empty)).toArray

```

**Comment by ajaynagesh** [comment]
I could run this test, thanks @kwalcock. I will comment the lines, run and report the results soon ...

**Comment by ajaynagesh** [comment]
@kwalcock  Do I need to comment the entire `OntologyLeafNode` class ? With your suggested changes I am getting the following error: 

screen shot 2018-10-02 at 8 05 13 pm

**Comment by kwalcock** [comment]
Sorry, just the /*names ++ */ part.

**Comment by ajaynagesh** [comment]
I did not read your code snippet correctly! Thanks!

**Comment by ajaynagesh** [comment]
With the parents removed (only leaves retained), I get identical performance on the test set i.e **64.06%** 

I checked that there are some differences in the outputs produced, just as a sanity check to ensure I am not plotting the same run again.

**Comment by bsharpataz** [comment]
Ok gentlemen.  I am going to try making a change to the grounding procedure, which will remove the text from any attachment trigger+quantifiers from the text used to ground.  What version of what branch/master should I start with?  And @ajaynagesh when I am done, I'll push it here and perhaps you can see how it affects the grounding precision?

**Comment by kwalcock** [comment]
@ajaynagesh, I assume the most recent test without the node names was with the adjectives so that the conclusion might be to skip the node names and leave out adjectives, but possibly keep the consistency.  I was waiting for @MihaiSurdeanu to make a ruling before doing anything.  It shouldn't be long, @bsharpataz, and then it will be in master.

**Comment by MihaiSurdeanu** [comment]
I am confused by Keith's latest comment. Can somebody please summarize the latest grounding results in this thread for the configurations tested?
Thanks!

**Comment by kwalcock** [comment]
master: 69.27%
kwalcock-canonical: 66.67%
kwalcock-canonical-adj: 64.06%
With the parents removed (only leaves retained), I get identical performance on the test set i.e 64.06%

I just wonder if the last is kwalcock-canonical-noParents or kwalcock-canonical-adj-noParents.  Probably the latter.

**Comment by bsharpataz** [comment]
you know, we could also try using the same intuition as what I did in the mapper --> add in (interpolate in) a weighted avg of the similarities between the extraction canonical name and the ancestors of the node (I used reciprocal rank for the weights)....
we can try that once it gets merged too....

**Pull request merged**
