### PR TITLE
Pt rules

### PR DESCRIPTION
**Pull request by gcgbarbosa**
@kwalcock Is that ok if in TestResources.scala we don't run utf8 checks on eidos.conf, reference.conf and wmseed.conf? We changed it to check only the references/english folder for unicode.

### CODE REVIEW

**Comment by kwalcock** [comment]
That's a fine idea.  Those few files usually aren't a problem and now neither is Portuguese.

**Comment by kwalcock** [comment]
I just wonder about this change to EidosActions which doesn't look specific to Portuguese.  Does the first regular expression overmatch something?

    "^cc".r, =>  "^cc$".r,

**Comment by gcgbarbosa** [comment]
I guess "^cc".r overmaches ccomp. @bsharpataz is that right?

**Comment by bsharpataz** [comment]
yep -- that was a good fix! for english too!

**Comment by kwalcock** [comment]
Thanks all.  I'll press the button then.

**Pull request merged**
