### PR TITLE
Egoitz test2

### PR DESCRIPTION
**Pull request by EgoLaparra**
- Maintain copula when avoiding verbs with arguments: "was a major shock" 
- Avoid verbal affect triggers: "impacting pasture"
- Avoid nmod_during: "shock during the last agricultural season"

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@bsharpataz: can you please take a look at the changes to avoidLocal?

**Comment by kwalcock** [comment]
Thanks.  I am still blissfully/painfully unaware of what side-effects such a change may cause.

**Comment by bsharpataz** [comment]
hey guys -- @EgoLaparra the change does make this sentence pass, but it's bc _shock_ has an outgoing _nsubj_ even though it's a noun.  the fix you have is maybe not as general as I'd like, but we can perhaps do this change instead: 

      # avoid verbs with arguments
      [outgoing=/^nsubj/ & tag=/^V/]

can you try that and see if your tests still pass?  it seems to have the same result on my branch

**Comment by EgoLaparra** [comment]
@bsharpataz  it worked fine!

**Comment by bsharpataz** [comment]
great!  I think I'm good with it all now -- @MihaiSurdeanu ?

**Comment by MihaiSurdeanu** [comment]
@EgoLaparra: can you please resolve this conflict?

**Comment by EgoLaparra** [comment]
Done.

**Pull request merged**
