### PR TITLE
Adding the 100 core WHO Health Indicators

### PR DESCRIPTION
**Pull request by ajaynagesh**
Formatted it as a yaml file. 

I did not add it as an ontology though (with 'OntologyNode:' and 'examples' etc) since I did not know whether this will be used as an ontology. Do let me know if this needs to be made as an 'ontology' yaml file 

Also I retained the hierarchy present in the original source (added as a comment in the yaml file) 

Source: https://www.who.int/healthinfo/indicators/2015/100CoreHealthIndicators_2015_infographic.pdf?ua=1

### CODE REVIEW

**Comment by ajaynagesh** [comment]
sure. @MihaiSurdeanu : do I need to add an OntologyNode to every indicator ? 

like this: 

```
- WHO Core Health Indicators: #lvl 0
  - OntologyNode: 
    - Health Status: #lvl 1
      - OntologyNode:
        - Mortality by age and sex: #lvl 2
          - OntologyNode:
             examples: 
             - Life expectancy at birth
             name: Life expectancy at birth #lvl 3
```

from 

```
- WHO Core Health Indicators: #lvl 0
  - Health Status: #lvl 1
    - Mortality by age and sex: #lvl 2
      - Life expectancy at birth #lvl 3
```

Since each of these are not 'examples' as in the un_ontology, nor are they 'descriptions' as in the wdi_ontology.

**Comment by MihaiSurdeanu** [comment]
@ajaynagesh: I believe you need to have an OntologyNode just for the terminal nodes. @bsharpataz ?

**Comment by ajaynagesh** [comment]
Ok. 

So will change it to: 

```
- WHO Core Health Indicators: #lvl 0
  - Health Status: #lvl 1
    - Mortality by age and sex: #lvl 2
      - OntologyNode:
         examples: 
         - Life expectancy at birth
         name: Life expectancy at birth #lvl 3
```

**Comment by bsharpataz** [comment]
yeah, looks good, thanks!

**Comment by ajaynagesh** [comment]
I have created the file with the appropriate Eidos ontology format

**Pull request merged**
