### PR TITLE
Allow for grounding to multiple ontologies

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
This is the initial design/version.  Some example output is below.  I need to catch up on the JSON-LD thread to check what else might need to change.  @ajaynagesh, can you take a look at the configuration file and the code?  @adarshp, this involves a change in the output format, so heads up.  Who else needs to eventually know?

```jsonld
  }, {
    "@type" : "Entity",
    "@id" : "_:Entity_3",
    "labels" : [ "NounPhrase", "Entity" ],
    "text" : "trade",
    "rule" : "simple-np++Increase_ported_syntax_1_verb",
    "canonicalName" : "trade",
    "groundings" : [ {
      "@type" : "Groundings",
      "name" : "un",
      "values" : [ {
        "@type" : "Grounding",
        "ontologyConcept" : "/entities/human/livelihood",
        "value" : 0.506400226133985
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/entities/human/government/government_entity",
        "value" : 0.4335030428381624
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/entities/human/government/government_actions",
        "value" : 0.35248245566498776
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/entities/GPE",
        "value" : 0.327215635838136
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/entities/human/financial/economic/economy",
        "value" : 0.3247794861278511
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/events/human/human_migration",
        "value" : 0.3230934865580204
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/entities/human/financial/economic/market",
        "value" : 0.3134656429486194
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/entities/human/financial/economic/technology",
        "value" : 0.2541643034638628
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/events/human/intervention/intervention",
        "value" : 0.23562084330727118
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/entities/human/infrastructure/transportation/transportation_methods",
        "value" : 0.22344509839982413
      } ]
    }, {
      "@type" : "Groundings",
      "name" : "fao",
      "values" : [ {
        "@type" : "Grounding",
        "ontologyConcept" : "/events/Value/Value of food imports over total merchandise exports (%) (3-year average)",
        "value" : 0.4484180772282565
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/events/Import Value/Sawnwood, coniferous",
        "value" : 0.36208516682431324
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/events/Value/Cereal import dependency ratio (%) (3-year average)",
        "value" : 0.3412391922109715
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/events/Annual growth US$/Agriculture, forestry, fishing (Central Government)",
        "value" : 0.3312396510718772
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/events/Production/Meat, Total",
        "value" : 0.329875682245146
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/events/Gross Production Value (constant 2004-2006 1000 I$)/Meat, game",
        "value" : 0.31703975643631066
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/events/Value US$/Total FDI inflows",
        "value" : 0.3107626466792807
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/events/Direct emissions (CO2eq) (Manure applied)/Cattle, dairy",
        "value" : 0.305900765970622
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/events/Direct emissions (CO2eq) (Manure management)/Cattle, dairy",
        "value" : 0.305900765970622
      }, {
        "@type" : "Grounding",
        "ontologyConcept" : "/events/Direct emissions (N2O) (Manure management)/Cattle, dairy",
        "value" : 0.305900765970622
      } ]
    } ],
    "provenance" : [ {
      "@type" : "Provenance",
      "document" : {
        "@id" : "_:Document_14"
      },
      "sentence" : {
        "@id" : "_:Sentence_15"
      },
      "positions" : {
        "@type" : "Interval",
        "start" : 11,
        "end" : 11
      }
    } ],
    "states" : [ {
      "@type" : "State",
      "type" : "INC",
      "text" : "improve"
    } ]
  }, {
```

**Comment by MihaiSurdeanu** [comment]
Looks good to me. This example should be discussed in the JSON-LD issue as well, so BBN is aware of it.

**Comment by adarshp** [comment]
@kwalcock : Thanks for the heads-up! This looks good to me. @bgyori should know about this as well, since changes will need to be made to the INDRA JSON-LD processors. @kwalcock : I take it this is not the final version yet, right? Please let me know when convergence is reached so that @bgyori or I can start modifying on the INDRA processor.

**Comment by kwalcock** [comment]
I'll merge it then.  We seem to be storing the ontologies in GitHub even though the vectors are not.  Without those, the ontologies are not used.  However, it's important to be able to see and comment on the ontologies, so it seems reasonable to "publish" them here to start.  Since there are now multiple instances, it might be a good idea to create an ontologies directory, though.

**Pull request merged**
