### PR TITLE
Allow some Portuguese Unicode

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by bsharpataz** [comment]
adding @marcovzla bc he designed Odin, so he can weigh in about what Odin can/can't handle.  If Odin is fine (I think it is?) then I feel like we prob shouldn't add a restriction/limitation in Eidos?

**Comment by kwalcock** [comment]
I was thinking more of Processors and everything that it depends on, like Stanford NLP.  If we analyze "The α and ω are beginning and end." the words are "The alpha and omega are beginning and end" and any grammar with α or ω will probably? not match.  Someone has to "sign off" in order to get the test to pass.  But change as needed, including removing the test.

**Comment by bsharpataz** [comment]
Yeah, i guess I was thinking that sometimes you want to make your grammar able to handle anything, unicode or not.  @marcovzla can you help decide when you get a chance?  You have the Odin/Reach experience to throw behind this convo :)
btw -- thanks @kwalcock for being thorough in what you do!

**Comment by kwalcock** [comment]
This issue doesn't seem important enough to delay the Portuguese PR.  I'm getting tempted to merge this just so the other one can pass its tests.

**Comment by bsharpataz** [comment]
yeah, let's go ahead and do it this way for now, and later we can revisit
the issue of unicode in the resources in general (perhaps at a meeting)

**Pull request merged**
