### PR TITLE
Change .sbtopts to .jvmopts because it works on Windows

### PR DESCRIPTION
**Pull request by kwalcock**
Can some people try this out?  Namely, rename .sbtopts to .jvmopts on your Macintosh or Linux computer and see if it works just as well?  It appears to be one way to keep the source distribution compatible across operating systems, assuming it works.  Thanks for trying.

### CODE REVIEW

**Comment by bsharpataz** [comment]
bsharp@Beckys-MacBook-Pro ~/github/eidos (bullets)]$ sbt test
Unrecognized option: -J-Xmx3g
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by kwalcock** [comment]
Sorry, just -Xmx6g.

**Comment by bsharpataz** [comment]
I think it works -- set it to 1g and got a bunch of java heap space OOM
errors :)
not the *most* thorough diagnostic, but.....

**Comment by bsharpataz** [comment]
and back at 6G works swimmingly

**Pull request merged**
