### PR TITLE
brat now shows locations

### PR DESCRIPTION
**Pull request by EgoLaparra**

### CODE REVIEW

**Comment by bsharpataz** [comment]
can you by any chance add a screen shot?

**Comment by kwalcock** [comment]
I'll probably be making one to add to the README.md file.

**Comment by marcovzla** [comment]
Oh, so you guys modified `visualizer.js` to handle `timexs` and `geoexps`. That's the part I was missing the other day. Mystery solved :)

**Comment by kwalcock** [comment]
I was looking for a good example and this happened:

image

Should I be worried?

**Comment by kwalcock** [comment]
This looks nice, though:
image

**Comment by EgoLaparra** [comment]
How is the output in "Found Geolocations"?

**Comment by MihaiSurdeanu** [comment]
The overlapping TIMEX and GEOLOC look problematic to me. @EgoLaparra ?

**Comment by EgoLaparra** [comment]
The geoparser identifies 2019 in that sentence as a geolocation. This is not a problem of the brat visualization. Maybe this is solved by the new model trained by @vikas95.

**Pull request merged**
