### PR TITLE
Removing obsolete FAO and WDI ontologies

### PR DESCRIPTION
**Pull request by adarshp**
This PR removes the obsolete FAO and WDI ontologies - the variables in them are now subsumed by the MITRE12 ontology.

### CODE REVIEW

**Comment by bgyori** [comment]
I agree with @bsharpataz in that the inclusion of these mappings can be turned on/off using the config. One advantage of the WDI and FAO mappings is that they correspond to data entries in those sources directly so it might make sense to keep them around just in case.

**Comment by kwalcock** [comment]
Is there consensus on this?

**Comment by BeckySharp** [comment]
Ok, I agree with @bgyori , @adarshp i think i’ll close for now but we can always reopen?

**Comment by adarshp** [comment]
@BeckySharp sure! I have reverted the removal of the files.

**Pull request merged**
