### PR TITLE
Help Metal into GeoNormFinder

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
This shows where/how I suggest to put the code into GeoNormFinder.  A setting in eidos.conf controls whether the Metal version or the GeoLocationExtractor version is used or not.  This code gets as far as trying to load the model, but doesn't seem to return from that for at least 1/2 hour on my computer.  Perhaps it will work differently on another computer.  MetalGeoExtractor.extract has not been tested.  I just made sure that it compiles.  It probably needs some work.

**Comment by kwalcock** [comment]
Metal is now also running on my computer, so I'll check up on some of the failing tests.

**Comment by MihaiSurdeanu** [comment]
Nice!


On July 7, 2020 at 5:49:19 PM, Keith Alcock (notifications@github.com)
wrote:

Metal is now also running on my computer, so I'll check up on some of the
failing tests.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/eidos/pull/885#issuecomment-655214825>, or
unsubscribe

**Comment by kwalcock** [comment]
@vikas95, these few tests are failing, probably due to geolocation issues.  You should be able to run them in IntelliJ and watch particularly MetalGeoExtractor.extract().  TestJLDSerializer and TestGeonorm are probably the easiest to figure out and perhaps when those work, some of the others will as well.  You can compare to the previous implementation by setting useMetal = false in eidos.conf.  There's also TestMetal where you can add completely new tests on the raw Metal object.  HTH.

If this code is reasonable, you can merge it into your metalLocation branch and continue working there.

```
[error] Failed tests:
[error]         org.clulab.wm.eidos.text.english.eval6.TestDoc5
[error]         org.clulab.wm.eidos.serialization.jsonld.TestJLDSerializer
[error]         org.clulab.wm.eidos.text.english.eval6.TestDoc2
[error]         org.clulab.wm.eidos.text.english.eval6.TestDoc3
[error]         org.clulab.wm.eidos.text.english.eval6.TestDoc1
[error]         org.clulab.wm.eidos.system.TestGeonorm
[error]         org.clulab.wm.eidos.text.english.cag.TestCagP2
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 517 s, completed Jul 7, 2020 6:18:12 PM
```

**Pull request closed without merging**
