### PR TITLE
Exporter fix

### PR DESCRIPTION
**Pull request by BeckySharp**
small bugfix on exporter i had done ahead of the last eval but forgot to push, also a python script for concating the eval files together for uploading to gdrive.

### CODE REVIEW

**Comment by kwalcock** [comment]
A PrintWriter should flush itself automatically on close.  Did you observe otherwise?  Certainly won't hurt though.

**Comment by BeckySharp** [comment]
> A PrintWriter should flush itself automatically on close. Did you observe otherwise? Certainly won't hurt though.

I did, but to be fair, I added the flush and close at the same time, I for some reason assumed the PrintWriter access method in Eidos made one that was "closeable" (or whatever the name was), I thought I had remembered you adding a bunch of syntactic sugar stuff so that things closed themselves, but I assumed wrong...

**Comment by kwalcock** [comment]
You're keeping me honest.  I should have looked harder.  Rather than passing in a prefabricated PrintWriter into the constructor of that Exporter, you should probably just pass in `filename + ".ground.csv"` from ExportUtils.getExporter.  Then in the export function, locally do the
```scala
    import org.clulab.wm.eidos.utils.Closer.AutoCloser
    
    FileUtils.printWriterFromFile(filename).autoClose { printWriter =>
      // Header
      pw.println(header)
      annotatedDocuments.foreach(printTableRows(_, pw, reader))
      pw.println()
    }
```
Does that make sense?  close() to me is one of those code smell things.

**Comment by kwalcock** [comment]
I'm handling the nitpicky thing above along with adding some CSV utilities that were almost ready to commit anyway.

**Pull request merged**
