### PR TITLE
remove extra parse

### PR DESCRIPTION
**Pull request by BeckySharp**
@zupon we don't need this re-parse anymore, right?

### CODE REVIEW

**Comment by kwalcock** [comment]
```
04:45:12.106 [ForkJoinPool-1-worker-15] DEBUG org.clulab.dynet.Metal - Loading MTL model from org/clulab/processors/clu/mtl-en-srla-avg-e3e5e2e6e4 complete.
04:45:12.106 [ForkJoinPool-1-worker-15] DEBUG org.clulab.dynet.Metal - Loading MTL model from org/clulab/processors/clu/mtl-en-pos-chunk-srlp-avg-e6e1e11e5e7...
04:45:15.620 [ForkJoinPool-1-worker-15] DEBUG org.clulab.dynet.Metal - Loading MTL model from org/clulab/processors/clu/mtl-en-pos-chunk-srlp-avg-e6e1e11e5e7 complete.
04:45:15.626 [ForkJoinPool-1-worker-15] DEBUG org.clulab.dynet.Metal - Loading MTL model from org/clulab/processors/clu/mtl-en-ner-avg-e10e12e8e3e2...
04:45:17.414 [ForkJoinPool-1-worker-15] DEBUG org.clulab.dynet.Metal - Loading MTL model from org/clulab/processors/clu/mtl-en-ner-avg-e10e12e8e3e2 complete.
04:45:23.517 [ForkJoinPool-1-worker-17] INFO  o.c.w.e.groundings.DomainHandler$ - Processing yml ontology with parents from /org/clulab/wm/eidos/english/ontologies/wm_flat_metadata.yml...
04:45:23.518 [ForkJoinPool-1-worker-17] INFO  o.c.wm.eidoscommon.utils.Sourcer$ - Sourcing resource file:/var/jenkins_home/.cache/coursier/v1/https/jitpack.io/com/github/WorldModelers/Ontologies/master-SNAPSHOT/Ontologies-master-SNAPSHOT.jar!/org/clulab/wm/eidos/english/ontologies/wm_flat_metadata.yml
04:45:36.143 [ForkJoinPool-1-worker-11] INFO  o.c.wm.eidoscommon.utils.Sourcer$ - Sourcing resource /var/jenkins_home/workspace/eidos_remove_extra_annotate/target/scala-2.11/classes/org/clulab/wm/eidos/english/sentenceClassifier/sentence_classifier_idf_weight_1000_20000.txt
[info] - should have 6 non-negative scores *** FAILED ***
[info]   java.util.NoSuchElementException: None.get
[info]   at scala.None$.get(Option.scala:347)
[info]   at scala.None$.get(Option.scala:345)
[info]   at org.clulab.wm.eidos.groundings.grounders.SentenceHelper.<init>(SRLCompositionalGrounder.scala:309)
[info]   at org.clulab.wm.eidos.groundings.grounders.SRLCompositionalGrounder.groundSentenceSpan(SRLCompositionalGrounder.scala:127)
[info]   at org.clulab.wm.eidos.groundings.grounders.SRLCompositionalGrounder.groundSentenceSpan(SRLCompositionalGrounder.scala:122)
[info]   at org.clulab.wm.eidos.groundings.grounders.SRLCompositionalGrounder.groundEidosMention(SRLCompositionalGrounder.scala:109)
[info]   at org.clulab.wm.eidos.groundings.OntologyHandler$$anonfun$3.apply(OntologyHandler.scala:41)
[info]   at org.clulab.wm.eidos.groundings.OntologyHandler$$anonfun$3.apply(OntologyHandler.scala:39)
[info]   at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
[info]   at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
[info]   ...
```

```
[info] (De)serialization
[info] - should handle the relevance *** FAILED ***
[info]   java.util.NoSuchElementException: None.get
[info]   at scala.None$.get(Option.scala:347)
[info]   at scala.None$.get(Option.scala:345)
[info]   at org.clulab.wm.eidos.groundings.grounders.SentenceHelper.<init>(SRLCompositionalGrounder.scala:309)
[info]   at org.clulab.wm.eidos.groundings.grounders.SRLCompositionalGrounder.groundSentenceSpan(SRLCompositionalGrounder.scala:127)
[info]   at org.clulab.wm.eidos.groundings.grounders.SRLCompositionalGrounder.groundSentenceSpan(SRLCompositionalGrounder.scala:122)
[info]   at org.clulab.wm.eidos.groundings.grounders.SRLCompositionalGrounder.groundEidosMention(SRLCompositionalGrounder.scala:109)
[info]   at org.clulab.wm.eidos.groundings.OntologyHandler$$anonfun$3.apply(OntologyHandler.scala:41)
[info]   at org.clulab.wm.eidos.groundings.OntologyHandler$$anonfun$3.apply(OntologyHandler.scala:39)
[info]   at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
[info]   at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
[info]   ...
```

**Comment by BeckySharp** [comment]
🤞  that https://github.com/clulab/processors/pull/489 fixed this

**Comment by BeckySharp** [comment]
ok @kwalcock I seem to be missing a dynet initialization? thoughts?
Does FastNLP use it?

**Comment by MihaiSurdeanu** [comment]
Yes, call this before creating the processor:
https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/dynet/Utils.scala#L44

**Comment by BeckySharp** [comment]
woo hoo! merging then?
@kwalcock this should make reading much faster I hope

**Pull request merged**
