### PR TITLE
Egoitz season modifiers

### PR DESCRIPTION
**Pull request by EgoLaparra**
- Look for season modifiers, e.g. "late" in "late rainy season".
- Add or subtract months in the normalization of season expressions according to the values in `seasons-db.yml`.

### CODE REVIEW

**Comment by kwalcock** [comment]
Thanks, @EgoLaparra.  It's too bad we didn't get to talk about this development this morning.  Is it something Mihai would want performance numbers for so that we know it's an improvement?  Should I want performance numbers to know that it only added 50 bytes to the file size and 0.1 seconds to processing time?  So far I did notice one strange `preamture: -1` and wonder whether `premature` is meant.  I will check and test the code fairly soon.

**Comment by MihaiSurdeanu** [comment]
i agree. Numbers would be nice :)

**Comment by EgoLaparra** [comment]
I fixed the typo. Thanks for catching it!

**Comment by kwalcock** [comment]
@EgoLaparra, I've resolved the conflicts locally.  There's an EvalSeasonNorm that is called up via TestEvalSeasonNorm, which is normally disabled,  When the test gets enabled, EvalSeasonNorm tries to access a file `Ethiopia_Food_Security_Outlook_1-Feb-17.csv` that doesn't seem to be in the repo.  Can we add that?  It looks like it should be in `/org/clulab/wm/eidos/english/context/timenormeval/` next to `gold_timenorm.csv`.  An exception is thrown without it.

**Comment by EgoLaparra** [comment]
Great, I forgot to add the test files. I've pushed `Ethiopia_Food_Security_Outlook_1-Feb-17.csv` and `Ethiopia_Food_Security_Outlook_1-Feb-17.txt`. The latter has the text input for the evaluation, it won't work without it.

**Comment by kwalcock** [comment]
Thank you!  It seems to work now.

**Pull request merged**
