### PR TITLE
Raps1

### PR DESCRIPTION
**Pull request by hclent**
My first effort to convert RAPS tests to the new eidos testing convention. 

First I added myself in `TestUtils` so that I can be tagged on a test.

Second I renamed `TestModifications` to `TestRaps` to match the convention `TestCag` for the CAG tests. 

Finally, I used the new testing methods in `GraphSpec` and `TestUtils` to update the first test. 

I'm currently unsure why this can't automatically merge? I'll investigate this but please let me know if you see what I need to change to merge it easier. Thanks!

### CODE REVIEW

**Comment by kwalcock** [comment]
It's just that

    object Heather extends Tag(tagName)

should now looks like

    object Heather extends TesterTag

The GitHub GUI does a pretty good job showing this.  Can you try it out?

**Comment by kwalcock** [comment]
I think that some problems might show up eventually.  This good code

val credit = newNodeSpec("well-functioning agricultural credit", newIncrease("Better") )

can be updated to be

val credit = NodeSpec("well-functioning agricultural credit", Inc("Better") )

now.  An import might need to change.  Sorry for the moving target.

**Comment by bsharpataz** [comment]
@hclent would you like me to help with the merge?  just let me know if so!

**Comment by hclent** [comment]
Thanks for getting back to me @kwalcock and @bsharpataz! Sorry for the delay, but I've finally resolved the merge conflict to be `object Heather extends TesterTag`. @bsharpataz Does the merge look good? 

@kwalcock, would you like me to fix the code to be ` NodeSpec("well-functioning agricultural credit", Inc("Better") )` before the PR is accepted? It seems like then I would need to delete this PR, make the changes, then start another PR? Alternatively, I can put this change in my next PR. Let me know what you think is best!

**Comment by hclent** [comment]
Alright, I updated the changes and now Travis is passing! My apologies for the somewhat ugly git history... I had to merge the changes from the git conflict back into the `raps1` branch... 

@kwalcock and @bsharpataz please review at your convenience and let me know if there's anything else I need to do to get the PR accepted. Then I can delete the branch and move on!

**Comment by kwalcock** [comment]
You're being merged.  Thanks!

**Pull request merged**
