### PR TITLE
Added Properties Attachment

### PR DESCRIPTION
**Pull request by bsharpataz**
Added properties attachment... The list is very incomplete (Property.tsv) but I am hopeful that it's a start.  The current code uses the lexiconNER to find properties, but that may or may not be ideal.  The attachments make it to the JSONLD, as with the example below.

NOTE:
- the grounding strategy has not been modified yet, that will be in an upcoming PR
- I modified the testing framework to ignore these for now, as we shouldn't rewrite all the tests until we have something more stable I think
- as I was adding this I was thinking that the attachment finding/adding actions could likely be refactored/cleaned/unified... any chance someone awesome like @kwalcock could help with this in a subsequent PR?

@bgyori @adarshp @ajaynagesh @ZhengTang1120 FYI

JSON_LD for `Rainfall increases the price of puppies.`:
```
...
{
    "@type" : "Extraction",
    "@id" : "_:Extraction_3",
    "type" : "concept",
    "subtype" : "entity",
    "labels" : [ "Concept", "Entity" ],
    "text" : "price of puppies",
    "rule" : "simple-np++property-lexiconner++Increase_ported_syntax_1_verb",
    "canonicalName" : "price puppy",
    "provenance" : [ {
      "@type" : "Provenance",
      "document" : {
        "@id" : "_:Document_1"
      },
      "documentCharInterval" : [ {
        "@type" : "Interval",
        "start" : 24,
        "end" : 39
      } ],
      "sentence" : {
        "@id" : "_:Sentence_1"
      },
      "positions" : [ {
        "@type" : "Interval",
        "start" : 4,
        "end" : 6
      } ]
    } ],
    "states" : [ {
      "@type" : "State",
      "type" : "INC",
      "text" : "increases",
      "provenance" : {
        "@type" : "Provenance",
        "document" : {
          "@id" : "_:Document_1"
        },
        "documentCharInterval" : [ {
          "@type" : "Interval",
          "start" : 10,
          "end" : 18
        } ],
        "sentence" : {
          "@id" : "_:Sentence_1"
        },
        "positions" : [ {
          "@type" : "Interval",
          "start" : 2,
          "end" : 2
        } ]
      }
    }, {
      "@type" : "State",
      "type" : "PROP",
      "text" : "price"
    } ]
...
```

### CODE REVIEW

**Comment by bsharpataz** [comment]
@MihaiSurdeanu I agree on both points -- re: naming the file, it's the rule for quantifiers and for properties, what they have in common is that they are both found using LexiconNER... i don't love it, but i wasn't sure I wanted like, several files with essentially identical functioning... IDK the right solution

re: incomplete -- YES! I was hoping @ZhengTang1120 or @ajaynagesh would fill in some more...?

**Comment by MihaiSurdeanu** [comment]
@ajaynagesh: can you please try to expand the Properties.tsv file with info from Maria's ontology?
Meanwhile, @bsharpataz: Ok to merge this.

**Comment by kwalcock** [comment]
Thanks for merging these, especially if Mihai has approved.  Does this one need some additional documentation on the JSONLD Wiki page?  Is it just like an INC or DEC?

**Comment by bsharpataz** [comment]
thanks for being gracious!
Yes -- it should be documented on the wiki, and yes, it's like Inc/dec
though I noticed that there doesn't seem to be provenance propogated...?
which is fine with *me*! :)

**Comment by ajaynagesh** [comment]
@MihaiSurdeanu: Sure working on it! I have a list of properties in the GSN that we can selectively incorporate into this. I am making a list now.

**Comment by ajaynagesh** [comment]
The GSN gives us the following properties: 

```
acceleration
activity-per-mass_radioactivity
activity-per-volume_radioactivity
aerodynamic_conductance
age
albedo
altitude
amount-per-volume_capacity
angle
angular_frequency
angular_momentum
angular_speed
area
area_fraction
attenuation_coefficient
cell-equivalents_concentration
compressibility
count
count-per-hour_rate
count-per-mass_radioactivity
count-per-volume_radioactivity
count_concentration
curvature
depth
depth-vs-discharge_coefficient
depth-vs-discharge_exponent
depth-vs-half-width_exponent
diameter
diffusivity
dimensionless_number
displacement
distance
duration
dynamic_viscosity
elevation
emissivity_factor
energy
energy-per-area_density
energy-per-mass_density
energy-per-volume_density
energy_flux
enthalpy
expansion_coefficient
flattening_ratio
force
frequency
friction_coefficient
friction_factor
head
heat_capacity
heat_transfer_coefficient
height
hydraulic_conductivity
impulse
kinematic_viscosity
latitude
length
linear_speed
linear_velocity
longitude
mass
mass-per-area_rate
mass-per-mass_radioactivity
mass-per-time_capacity
mass-per-volume_capacity
mass-per-volume_density
mass-per-volume_rate
mass-per-width_rate
mass-specific_heat
mass-specific_heat_capacity
mass_concentration
mass_flux
mass_fraction
mass_rate
mass_ratio
mass_transfer_coefficient
mechanical_hardness
mixing_ratio
modulus
mole-specific_heat
mole_rate
momentum_transfer_coefficient
number_capacity
per-time_radioactivity
per-wavelength_emittance
perimeter
period
power
pressure
pressure_lapse_rate
price
radius
root_quantity
rotation_rate
s_coordinate
safety_rating
shape_factor
sinuosity
slip
slope
slope-vs-discharge_coefficient
slope-vs-discharge_exponent
sorptivity
specific_energy
speed-vs-discharge_coefficient
speed-vs-discharge_exponent
stomatal_resistance
strain
strain_rate
strength
stress
subsidence_rate
temperature
temperature_lapse_rate
thermal_expansion_coefficient
thickness
time
time_step
volume
volume-specific_heat_capacity
volume_flux
volume_fraction
volume_rate
vorticity
wavelength
weight
width
width-vs-discharge_coefficient
width-vs-discharge_exponent
year
```

**Comment by bsharpataz** [comment]
@ajaynagesh can you by any chance add these in a PR?

**Comment by ajaynagesh** [comment]
Sure!

**Pull request merged**
