### PR TITLE
PT hedging+transparent+stop

### PR DESCRIPTION
**Pull request by gcgbarbosa**
Fixed a problem with the negation, translated filtering files and updated rules.

### CODE REVIEW

**Comment by kwalcock** [comment]
I just wonder about `(depNegations).toSet` which must be an artifact left over from previous code.

**Comment by gcgbarbosa** [comment]
Thanks for pointing it out. I have cleaned it out.

**Comment by kwalcock** [comment]
OK.  I don't want this waiting here to slow you down, so I'll merge.

**Comment by kwalcock** [comment]
I see that this is a different branch than the previous pt-neg+tets.  It looks like next time I should maybe resume deleting the branch after merging.  Would you go ahead and delete remote branches pt-* if you're done with them and/or have local copies?  Thanks, @gcgbarbosa.

**Comment by gcgbarbosa** [comment]
Thanks @kwalcock. I deleted them, except for pt-tests because I am using it to synchronise the version of eidos I have in my machine and the version on the servers if i need to run something there. Idk if this is ok or if there is a better way to do that.

**Comment by kwalcock** [comment]
That's great.  I have a branch to do exactly the same.

**Comment by gcgbarbosa** [comment]
Awesome! Thanks.

**Pull request merged**
