### PR TITLE
Add a ParagraphSplitter

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
This isn't quite production code yet, but it digs deep into processors and it would be useful to get feedback before I clean it up.  There is more information at #654.

**Comment by kwalcock** [comment]
Thanks.  I think the reason for not doing it by subclassing was so that it can support Spanish and Portuguese as well.  The available pre and post processing steps I noticed were TokenizerSteps and the argument to that is an Array[RawToken] which leaves it without access to the text containing the whitespace.  I may well be wrong, of course, and suggestions welcome.  I can also show how it would look with that better access to Tokenizer arguments.  It is in a delicate place and it does seem important to get it right.

**Comment by MihaiSurdeanu** [comment]
Yeah, good point about the multilingual processors. In any case, this is not what I had in mind. Take a look at the custom tokenization postprocessor in BioNlpProcessor:

https://github.com/clulab/processors/blob/master/corenlp/src/main/scala/org/clulab/processors/bionlp/BioNLPProcessor.scala#L30

**Comment by kwalcock** [comment]
Yes, let's talk about it at the meeting, because I don't readily see what you mean.

In the meantime, risking infecting the itch that I'm scratching,  I'll add two other options with the issue that would be possible with slight changes to processors. #654

**Comment by kwalcock** [comment]
This was done in a different way which involves changes to processors.  This PR is being closed without merging.

**Pull request closed without merging**
