### PR TITLE
Hard-code rule priority to allow parse

### PR DESCRIPTION
**Pull request by kwalcock**
Remove keepMigrationEvents from config files

### CODE REVIEW

**Comment by kwalcock** [comment]
This fixes the configuration problem, but still a lot of tests are failing in TestMigrationSchema.  Most seem to be related to counts.

**Comment by BeckySharp** [comment]
hmmm... ok, I can try to dig in...

**Comment by BeckySharp** [comment]
or maybe --- @zupon can you or @maxaalexeeva (IDK who worked on the counts) look and suggest somewhere to dig in?

**Comment by maxaalexeeva** [comment]
Yes, I can try to look at that tomorrow!

**Comment by maxaalexeeva** [comment]
Becky, I mean we can dig in---no need for you to at least yet.

**Comment by kwalcock** [comment]
I'll keep looking as well then.  I wondered if it would ring a bell.

**Comment by BeckySharp** [comment]
thanks all!!

**Comment by maxaalexeeva** [comment]
wanted to start looking, but I guess now eidos comes with a glove vectors download (?) and my current internet is super slow (and I don't have access to jenkins output). Hope they will download by tomorrow and I can have a look at what's going on.

**Comment by kwalcock** [comment]
We can get you access to Jenkins.  It will be better if you can use a debugger, though.  You can comment out the glove dependency in build.sbt.  Then turn off ontologies.useW2V in eidos.conf.  Vectors aren't needed then.

**Comment by maxaalexeeva** [comment]
Thanks, @kwalcock!

**Comment by maxaalexeeva** [comment]
@kwalcock, I am still looking. There are some cases where it looks like some rules just didn't work---I will have to look at those later (either tonight or tomorrow at the latest), but there are two test sentences* where it looks like the group just did not expand. Could that have anything to do with the separation of expanders into concept and action? (I can investigate more later but have to go now). 

_85% of the new arrivals originated from Upper Nile State (Nasir, Longechuk or Mathiang, Ulang and Maiwut Counties), whilst 14% came from Jonglei State (Uror, Akobo and Ayod Counties)_

The tests related to the sentence with at least some nodes failing: _migration-originated_ through _migration-originated-5_ (with the exception of migration-originated-2, which was ignored anyway)

_Civilians caught in the fighting between armed actors first displaced into remote areas of the bush, then flee to Uganda, Kenya or the DRC over the course of a few months._

Relevant failing tests: _migration-supplemental-3_

**Comment by BeckySharp** [comment]
ok, expansion seems like a good place to start! and also maybe the global
action.
thanks -- are you still digging or should i tomorrow?

**Comment by maxaalexeeva** [comment]
I should be able to look more tomorrow late-ish afternoon, but if you happen to have  some time before then, feel free to have a look especially if you're familiar with the expander changes. Thanks!

**Comment by BeckySharp** [comment]
I went ahead and merged so we can consolidate things, but seems the issue is that the tests were written to have things like "85%" be represented as:
`val group1 = NodeSpec("85% of the new arrivals", CountSpec(85, CountModifier.NoModifier, CountUnit.Percentage))`
But what we get now is:

```
List(Concept, Entity) => 85% 
     ------------------------------ 
     Rule => simple-np 
     Type => TextBoundMention 
     ------------------------------ 
     Concept, Entity => 85% 
     * Attachments: COUNT("85 %", value=85.0, mod=NoModifier, unit=Percentage) 
```

Was there something explicitly being done to remove the `%` from the text? Or should we just change the test?

**Comment by maxaalexeeva** [comment]
@BeckySharp the intention with the group was to extract the complete natural lang info about the group (e.g., 85% of the new arrivals) and then get the info about count using a couple of actions (e.g., this https://github.com/clulab/eidos/blob/6ecb938b3a75c2ce72af11e9714e02ed897836e5/src/main/scala/org/clulab/wm/eidos/EidosActions.scala#L93). Sometime between merging migration branch into master and now, we lost the expansion from 85% to _85% of new arrivals_ (the test was passing). We could delete the new arrivals part to have the test pass, but that is not what the test was intended as and something might be wrong.
(A similar lack of expansion is with the civilians example---only _civilians_ was extracted and not the _cuaght in the fighting_)

I am hoping to look into this today more. Is there a pressing deadline on this? (e.g., we need this tomorrow)

**Comment by BeckySharp** [comment]
nope no deadline, and i into the expansion, thanks for letting me know the
intention

**Pull request merged**
