### PR TITLE
Properties obtained from GSN

### PR DESCRIPTION
**Pull request by ajaynagesh**
specifically from file 'quantitative_property.csv' .. 
sorted with the rest of the properties in 'Property.tsv'

### CODE REVIEW

**Comment by kwalcock** [comment]
@ajaynagesh, the word "displacement" in the properties seems to affect a test.  You may have time to look into it before I can.

**Comment by ajaynagesh** [comment]
Addressed the changes requested by Becky.

**Comment by ajaynagesh** [comment]
Oh I see... Will change this ... also will keep a copy of the old indicators ...

**Comment by bsharpataz** [comment]
@ajaynagesh when you finish this, can you also address the failing tests?  it could simply be fixed with merging the newest master in

**Comment by ajaynagesh** [comment]
@bsharpataz , merged the latest master into this branch as well as added the properties (with and without - in their names). Hopefully the tests will pass now.

**Comment by kwalcock** [comment]
@bsharpataz, are you happy with this now?

**Pull request merged**
