### PR TITLE
Test Python (without Scala)

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
This is an attempt to arrange for python unit testing for eidos.  This testing is only performed on the top level project right now.  Python files are expected to be in src/main/python and src/test/python.  The testPython task runs the tests.  All the files are first copied to target/python from which the tests are run with pytest.  testPython is not integrated into the normal test procedure, which continues to test only Scala/Java code.  Travis will test the python code and if you need to, just run `sbt testPython`.  See python.sbt for details.

**Review by MihaiSurdeanu — APPROVED** [review]
very nice!

**Comment by kwalcock** [comment]
I meant that Jenkins will test the Python code since that is being used for eidos.  Travis may be doing the ontologies.

**Comment by zupon** [comment]
Looks good! I'll try it out with the other scripts. Is this okay to merge?

**Pull request merged**
