### PR TITLE
modified entity constraints to allow for JJ entities

### PR DESCRIPTION
**Pull request by bsharpataz**
also: 
- removed last old test :/
- added a trigger @ajaynagesh  will need (as long as I was at it...)

### CODE REVIEW

**Comment by bsharpataz** [comment]
ps -- this will affect @mithunpaul08 's test(s) too

**Comment by kwalcock** [comment]
I just wonder about the ignored tests.  Should the reason they are being ignored be documented or should they now be deleted?

**Comment by bsharpataz** [comment]
They are on the old framework... I don't know the answer.  @MihaiSurdeanu  do you care?

**Comment by bsharpataz** [comment]
I can also check to see if they're easily fixed...?

**Comment by kwalcock** [comment]
Could there just be a comment added that says
// This test is being ignored because... it is designed for an old framework, namely...
Ignore is a red flag and I think a short comment will save someone in the future a lot of questions.

**Comment by bsharpataz** [comment]
sure! I'll add!

**Pull request merged**
