### PR TITLE
additions to UN ontology

### PR DESCRIPTION
**Pull request by ajaynagesh**
EDIT: Completed the additions to UN ontology from 3 documents: 

1.  Slides 10-18 --> WM Twelve-Month Evaluation Scripts-Nov1-LH.pdf 
2. Slides 3-10 --> WM Twelve-Month Evaluation Storyboard_6October2018.ppt"  
3. Guide to South Sudan Data-2.doc  document

--------------------------
(old comment)
Additions from just one slide (slide #3) of "WM Twelve-Month Evaluation Storyboard_6October2018" PPT 

Generated quite a few new nodes and examples from just this one slide.  Wanted feedback on the level of detail captured and/or modifications (appended the new nodes with #ppt-#3 for easy identification)

If this is fine, I can go ahead and make more additions from the slides and the word document. 

Thanks!

### CODE REVIEW

**Comment by adarshp** [comment]
Also, if possible, please focus on making sure the entities/concepts in slides 10-18 `WM Twelve-Month Evaluation Scripts-Nov1-LH.pdf` (it's in the Google Drive folder) are represented in the ontology - most of them should already be there, but we don't want to miss important ones...

**Comment by ajaynagesh** [comment]
thanks for your comments @adarshp and @MihaiSurdeanu ! 

Continuing to work on the same branch with the modifications suggested ...

**Comment by ajaynagesh** [comment]
@MihaiSurdeanu @adarshp @bsharpataz: Completed this exercise (of adding nodes/examples to UN ontology). Please review and let me know your comments...

**Comment by kwalcock** [comment]
@ajaynagesh, is that a sufficient number of approvals or should I wait on Becky?  Perhaps she has approved in person.

**Comment by ajaynagesh** [comment]
Hi @kwalcock I think you could merge this, given Adarsh and Mihai have approved..

**Comment by ajaynagesh** [comment]
@bsharpataz, Thanks! opened a new PR with the modifications suggested. https://github.com/clulab/eidos/pull/511

**Pull request merged**
