### PR TITLE
Refactor actions

### PR DESCRIPTION
**Pull request by BeckySharp**
This is a start to refactoring the EidosActions (aimed at making eidos more modular and so domain and task independent). This is by no means "the solution" but just (I think) a step in the right direction.

**NOTE 1**: I think this _does_ allow for using eidos to extract *non-causal* events by disabling the coref (I think that corefHandler is the only place where explicit refs to "cause" and "effect" args are made)

**NOTE 2**: made from master, so after next round of PRs may need conflicts resolved

Highlights:
 - `fromConfig` constructor for EidosActions that makes expansion and coref not only optional but swappable (note the `useCoref` and `useExpansion` keys in config)
 - CorefHandler which should make coref approaches swappable (note the `corefType` key in config)
 - Slight changes to config again (sorry!) -- the placement of the `stopWordsPath` and `transparentPath` in `EidosSystem` block of config
- I _may_ have added some grammar tweaks to make 2 more tests pass, even though I completely agree that this was the wrong place to do it (i.e., I should have made it a separate PR...) :)

### CODE REVIEW

**Comment by kwalcock** [comment]
Having to resolve conflicts will teach me not to slack off ;-)  Still testing the previous conflict resolution...

**Comment by kwalcock** [comment]
@BeckySharp, are all the changes other than those to the rules thought to preserve behavior?  If so, I'll compare before and after just as a sanity check.  I think the code is looking better and better.

**Comment by BeckySharp** [comment]
> @BeckySharp, are all the changes other than those to the rules thought to preserve behavior? If so, I'll compare before and after just as a sanity check. I think the code is looking better and better.

yes -- they are, and if I had thought about it like that, I would have done the rule change commit on a diff PR for sure (lesson learned, thanks!).  Those rule changes are on a diff commit **I think** (https://github.com/clulab/eidos/commit/d915dba62bd1afee16c2bfcf136ccec41e883d34), though malheureusement not the _last_ commit.  Are you able to easily tease it apart?  Or do you want me to remove those changes chez moi and make a diff PR?

**Comment by BeckySharp** [comment]
also, thanks! :)

**Comment by kwalcock** [comment]
I can tease it out just enough for a test and I only noticed because I've done that several times myself and finally decided it might not be the best idea.  It looks like the cat walked across your keyboard.  I think you meant to type helaas.

**Comment by kwalcock** [comment]
The rule change resulted in minor changes to the output of 7/52 files.

**Comment by kwalcock** [comment]
I have no idea what is happening with all these configuration files.  I'm probably going to want to send this merge back to you, especially if I can figure out how to back out of the mess.

**Comment by BeckySharp** [comment]
I can work on the configs -- give me a min

**Comment by kwalcock** [comment]
Thank you!!!  Oops all you want.  I'll run a few more tests.

**Comment by BeckySharp** [comment]
@kwalcock mind if I merge?  I'd like to work on something and would like to use this as a starting point

**Comment by kwalcock** [comment]
Sorry, someone was distracting me.

**Pull request merged**
