### PR TITLE
Maintain grounders

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
@zhengzhongliang, to what extent are you still working on grounding?  That single grounding file should have been split into parts some time ago, but not while so many different people were working on it.  Have things slowed down enough that this PR won't cause you problems?  

@BeckySharp just FYI.  The ontologies are split up as well.  For both grounders and ontologies there are additional variations in different eidos forks and this hopefully helps with isolating the changes.

**Comment by zhengzhongliang** [comment]
Hi Keith,
Yes I am working on some final ideas of the grounder. It would be great if
I can have one more week to do those experiments. I think they will be done
by the world modeler meeting next week.

Best regards,
Zhengzhong

**Comment by kwalcock** [comment]
It can wait a little for Zhengzhong.  I've been lulled into complacency by Scala's C-style ability to include numerous classes in a single file.  It starts out being handy, but at some point there's an overload.  The JLD serializers will eventually meet a similar fate.

**Comment by zhengzhongliang** [comment]
Hi Keith,
Since I do not intend to change any major things in this branch (i.e., done with this for now), maybe you can start modifying it. Thanks for waiting for me.

Best regards,
Zhengzhong

**Comment by kwalcock** [comment]
Thanks, @zhengzhongliang.  I'll merge soon.  It shouldn't be too difficult to figure out where things have moved to.

**Pull request merged**
