### PR TITLE
Translate migration to canonical Scala

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
I left some things in there so that the output changes minimally.  Merged mentions, for example, lose their order and ties are less well handled.  Still in 52 documents, there were two changes of order, possibly because of the tiebreaker on orderMentions.

**Comment by BeckySharp** [comment]
@kwalcock  --
@maxaalexeeva  and I just modified the 2 failing tests, so that should fix things with that

**Comment by BeckySharp** [comment]
ps -- hope you didn't mind us mucking in _your_ branch, seemed like a good way to make sure they survived and fixed the tests overall

**Comment by kwalcock** [comment]
Not at all, especially if nobody else minds me having ransacked their branch when I merge this one.

**Pull request merged**
