### PR TITLE
Factor out parallelization code

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by BeckySharp** [comment]
@kwalcock just for my edification -- what prompted this factoring out? thanks!

**Comment by kwalcock** [comment]
Just too much repeated code and all my own fault.  The specification of number of threads may move to a configuration file or environment variable, etc.

**Comment by kwalcock** [comment]
Mostly I found a file Parallelizer.scala on my computer and wanted to get rid of it.

**Comment by BeckySharp** [comment]
:)

**Pull request merged**
