### PR TITLE
Compactize the patterns

### PR DESCRIPTION
**Pull request by kwalcock**
The compact version likes Arrays rather than Seq, so in haste I changed several of them.  If need be and provided time, they can be converted.

### CODE REVIEW

**Comment by kwalcock** [comment]
While testing I was reminded that a node like month is pretty much useless because none of the examples makes it through the filter (I think).  season isn't much better.  Is this a problem?

**Comment by bsharpataz** [comment]
> While testing I was reminded that a node like month is pretty much useless because none of the examples makes it through the filter (I think). season isn't much better. Is this a problem?

probably :)  but fwiw we're about to align the ontologies with BBN so I think I'll put that off til then

**Comment by bsharpataz** [comment]
@kwalcock I "fixed" the one test file (by marking the tests as failing -- we decided to remove the trigger that they relied on...).  Can you please help diagnose/fix the JSONLD failing tests? (or tell me if I need to do it bc you're busy).  Thanks!!

**Comment by bsharpataz** [comment]
@kwalcock on the `hackathon_int` branch I marked the tests that are failing as failingTest, so I am going to merge this in

**Pull request merged**
