### PR TITLE
Dup events

### PR DESCRIPTION
**Pull request by bsharpataz**
fix for duplicated entities and events in same span

I think fixes https://github.com/clulab/eidos/issues/147

### CODE REVIEW

**Comment by kwalcock** [comment]
The test case is forthcoming.  Should it only check for EventMentions with duplicate IDs?

**Comment by bsharpataz** [comment]
not id's prob... I guess events with the same label and span? if they have the same label and span, but diff triggers are we considering them to be duplicates? @MihaiSurdeanu

**Comment by MihaiSurdeanu** [comment]
Events should be considered duplicates if:
- They have the same spam.
- They have the same label.
- They have the same arguments (so it's a recursive function).

The trigger doesn't matter.

**Comment by MihaiSurdeanu** [comment]
(The trigger doesn't matter because it's captured in the event label already.)

**Comment by bgyori** [comment]
I checked out this branch and tested it locally, it definitely resolves #147 thanks!

**Comment by bsharpataz** [comment]
great!

**Pull request merged**
