### PR TITLE
Update the readme file

### PR DESCRIPTION
**Pull request by kwalcock**
It should be more complete and especially more accessible.  I hope that people aren't scared away because of sbt or Scala.  The file is easier to read by switching to the branch kwalcock-readme.

### CODE REVIEW

**Comment by kwalcock** [comment]
Here's my stab at #482.

**Comment by bsharpataz** [comment]
PT = Portuguese, I had a hard time too when i first joined those meetings!
:)

**Comment by kwalcock** [comment]
There are a couple of sentences about Portuguese in the Translating section.  Perhaps it should be featured more prominently.  I probably didn't do it justice and maybe I can volunteer @gcgbarbosa to contribute some of the exciting details.

**Comment by gcgbarbosa** [comment]
@kwalcock do you think this is good enough?

https://i.imgur.com/nm1FCp7.png

**Comment by kwalcock** [comment]
Cool!  I see lots of causes and effects at https://github.com/clulab/eidos/blob/kwalcock-readme/README.md#translating.  Was there any content further down the screen that is worth showing?  The other images on the page have a width of 1610 pixels, so your image is being shrunk more and is a little difficult to read.  I'm not sure how well the diagrams break between lines, but you're welcome to narrow the width and check it out.

**Comment by gcgbarbosa** [comment]
If I try to get the whole output of this sentence in one image it will be very large. Do you think it is a problem? 

Here is another image with 1610p of width: https://i.imgur.com/CzerApj.png

I can try to get another one with the whole output if needed.

**Comment by kwalcock** [comment]
Thanks!  More is not needed.  If you think it highlights your work better,
you are welcome to update the image.

**Comment by kwalcock** [comment]
I'll do the merge in the relatively near future unless, for instance, mean @bsharpataz finds fault.  After all, it was her idea ;-)

**Comment by gcgbarbosa** [comment]
Awesome! Thanks @kwalcock.

**Pull request merged**
