### PR TITLE
Remove gratuitous Unicode in resources and test for it

### PR DESCRIPTION
**Pull request by kwalcock**
Include not much used Sourcer to open files with UTF8 encoding

### CODE REVIEW

**Comment by kwalcock** [comment]
With this, it should not be necessary, as least as far as the rules are concerned, to do
export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
The program will run even with ASCII encoding.  There is code in Sourcer to enforce UTF8 in case it is found in some text file that we process.  I have not checked in changes to code that makes use of Sourcer because I have not found a good way to test it yet.

**Comment by kwalcock** [comment]
@bsharpataz, do you know why EidosActions tries first fromFile and then fromURL?  Are we allowing people to override the URL location with a file and falling back if it isn't there?  I'd like to make it the same as the others with just fromURL.

val source:BufferedSource = if (url == null) scala.io.Source.fromFile(new File(path)) else scala.io.Source.fromURL(url)

**Comment by bsharpataz** [comment]
I think it may have been so it could be run both in the IDE and with
sbt...?  to help with finding the file in the jar...? I'm not 100% sure but
I recall that one way of running things had trouble finding files in the
resources?
but FWIW people should be able to provide their own grammar/resource files
as easily as possible

**Comment by MihaiSurdeanu** [comment]
Fwiw, both the IDE and sbt should work with fromURL...

**Comment by kwalcock** [comment]
I've gone ahead and rerouted Eidos file access through this Sourcer thing where our standard of encoding any necessary Unicode characters as UTF-8 is codified.  It shouldn't break anything, but I haven't found a case where it is actually necessary except second-hand in the docker container.  This might allow inclusion of the special characters I just got rid of in the yaml files without requiring the environment setting.  Everything is read as a resource via URL.  We may well have to make an exception for the file of vectors, however.  That's coming up yet.

**Pull request merged**
