### PR TITLE
adding properties from icasa spreadsheet

### PR DESCRIPTION
**Pull request by ajaynagesh**
I am no domain expert. But I tried to adding some of the variables from the ICASA spreadsheet into the properties node of the un_ontology. The examples are made up by me based on what looked like commonsense. Feel free to ignore these variables if not necessary

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
I am not sure solar_radiation is a property? Hard to combine it with anything...
@ajaynagesh, @bsharpataz: what do you think?

**Comment by ajaynagesh** [comment]
@MihaiSurdeanu Had a similar feeling too. Since you mentioned in the mail, I thought it should be included. I could remove just this one. Others seem ok, except for depth (maybe) ..

**Comment by adarshp** [comment]
Solar radiation seems like an object rather than a property to me  - I think of it in the same way as rainfall, etc...

**Comment by MihaiSurdeanu** [comment]
I agree with Adarsh: it should be included in the ontology, just not as a property.
Maybe under weather, for the lack of a better non-terminal?

**Comment by ajaynagesh** [comment]
Moved the solar_radiation to weather...

**Pull request merged**
