### PR TITLE
Test more strange characters

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by BeckySharp** [comment]
thanks!

**Comment by kwalcock** [comment]
Hey, I wasn't ready yet!

**Comment by kwalcock** [comment]
To save myself from needing to track down problems later, I needed to kick this a little harder.  The code didn't have to change, but one thing led to another, and I was too lazy to recalculate the offsets.  Reject or revert as necessary.  I'm convinced that it works, though, and that it will probably keep working.  FYI the LUM version has a couple more variables, so it may look different there.  It's still in the kwalcock-caJson branch.  I'm not sure it will get back-ported, but it's available.

**Comment by BeckySharp** [comment]
well, then NOW thanks :)

**Comment by BeckySharp** [comment]
hope you don't mind that i merged it :) sorry -- got carried away!

**Comment by kwalcock** [comment]
A PR on your branch is yours to merge, repurpose, revert, reject, etc. :-)

**Pull request merged**
