### PR TITLE
[DART-1016] - Updating Dockerfiles to build wmexchanger distribution and package eidos dependencies in the base image

### PR DESCRIPTION
**Pull request by yanzv**

### CODE REVIEW

**Comment by yanzv** [comment]
@kwalcock Can you please squash merge the PR whenever you ready to merge. 
Thanks!

**Comment by kwalcock** [comment]
I'm still testing this.  The "dist" works very nicely.

**Comment by yanzv** [comment]
I've added one more commit to this PR and updated a field `sasl.jaas.config: ${KAFKA_CONSUMER_APP_SASL_JAAS_CONFIG}` to  `sasl.jaas.config: ${?KAFKA_CONSUMER_SASL_JAAS_CONFIG}` removed `APP` that is not part of the path for that config field

**Comment by kwalcock** [comment]
These changes went in with #1018, so I will eventually close this.

**Comment by kwalcock** [comment]
@yanzv, these should all have been merged in with #1018, but it will be difficult to tell, because they were squashed as requested.  You may want to look for the couple of minor changes I made which hopefully don't affect you.  I'll close this in the meantime.

**Pull request closed without merging**
