### PR TITLE
Mihai's changes on the Fan's latest ontology changes .. 

### PR DESCRIPTION
**Pull request by ajaynagesh**
also incorporating some comments like spelling corrections, adding 'storm' etc.. Discussed this with @bsharpataz .. so not adding her as the reviewer .. 

Planning to use this version for the creation of the gold dev set for grounding of the MITRE document mentions ..

### CODE REVIEW

**Comment by kwalcock** [comment]
@ajaynagesh, can you look at master's version and compare to what you started out with that may have been in an email attachment.  I'm concerned that you didn't start out with Fan's latest/last changes.

It looks like the file you just submitted has several blank lines, extra white space on the right, and it also seems to have CR/LF line endings.  Something may not be quite right.  (Maybe I messed something up.)

**Comment by ajaynagesh** [comment]
Hi @kwalcock, 

I think the differences are minimal and it captures all the changes which Mihai's made. There are a few stray spaces at the end of some lines (and a couple of empty lines) . Would that be a problem ? 

screen shot 2018-06-13 at 9 53 22 am

(the one the right is my changes in this PR compared to master on the left)

**Comment by ajaynagesh** [comment]
Hi @kwalcock: (@bsharpataz , @Fan-Luo ), I noticed an extra indentation after - Abiotic_resources:  (This is in the master branch and also in here - since it is based on the master branch)  

Could you please check ?

**Comment by kwalcock** [comment]
Is a push forthcoming?  If nobody else does it, I will make sure the line endings are LFs.

**Comment by Fan-Luo** [comment]
No push from my end.
I only fixed the extra indentation pointed out by Ajay.
Please see: https://github.com/clulab/eidos/commit/3fd94f1a367be3f3bfca20b8118abd22f35cdd7f <https://github.com/clulab/eidos/commit/3fd94f1a367be3f3bfca20b8118abd22f35cdd7f>

**Comment by kwalcock** [comment]
If someone has already committed to master, then this branch had better not go to master.  It should be closed.  In the version that recently went to master I do see "nAtuRAl ReSouRceS" for some reason.

**Comment by kwalcock** [comment]
I see that master's indentation was possibly fixed, but I don't know whether or not Ajay's changes were included at all.

**Comment by Fan-Luo** [comment]
For 'nAtuRAl ReSouRceS’ and misspelled ‘malaraia’, they are both from where Becky originally get for me.
I think it was from 'kwalcock-ontology branch' , according to the email Becky sent: 'Working from your kwalcock-ontology branch’.
I only extend several nodes, I did not do spelling check, etc.
By the way, I saw Ajay previously replied corrected  ‘malaraia’, but it is still there in master, do you want me to correct it? 
If yes, @Keith, do you want me to create another branch to make this change, instead of committed to master?

**Comment by keith** [comment]
(wrong keith)

**Comment by kwalcock** [comment]
Either way as long as you coordinate with others who are making changes.
This PR already has conflicts which I won't know how to resolve.

**Comment by MihaiSurdeanu** [comment]
Ajay,
Can you please solve these conflicts?

**Comment by bsharpataz** [comment]
not for malaria, but the weirdly cased natural resources I think was one of
the "high-freq" guys ajay merged in bc it appeared in UN reports (oddly
enough) -- though perhaps I'm mis-remembering?

**Comment by kwalcock** [comment]
I do remember now that 'nAtuRAl ReSouRceS’ is a repeat issue.  Sorry.  I should add a comment about that.

**Comment by ajaynagesh** [comment]
For some reason, I am not seeing any conflict when I pull @kwalcock's changes ? But I see this branch has conflicts on github.

**Comment by kwalcock** [comment]
This is merged without any guarantees.  It needed to be done.

**Comment by bsharpataz** [comment]
@kwalcock @ajaynagesh @MihaiSurdeanu 
what was the final status of this?  Do things need to be fixed/changed or are we fine?
thanks!

**Comment by MihaiSurdeanu** [comment]
I don’t know. Ajay?

**Comment by kwalcock** [comment]
It was fixed/changed and merged.  About fine I can't say much.

**Comment by ajaynagesh** [comment]
@MihaiSurdeanu @bsharpataz  These changes look fine to me when I compare it with the version I have. I think there was an issue in the indentation of some nodes from a previous version due to a commit by someone directly on the master, which @kwalcock fixed in this change.

**Comment by bsharpataz** [comment]
Great, thanks all!

**Comment by Fan-Luo** [comment]
Thanks for making this clear.
The only commit I made to master actually is to fix indentation.
I think Keith redid some of the work, and it is because of my miscommunication, which caused more work and unnecessary discussion.
I should also did data sanitization or at least pointed it out.
Sorry and thanks to Keith for fixed everything.

Fan

**Pull request merged**
