### PR TITLE
Making the webapp show increased NPs as green, decreased as red, and otherwise quantified as blue...

### PR DESCRIPTION
**Pull request by bsharpataz**
To be honest -- I'm not sure this is the best way to accomplish this, so @kwalcock if you have another, cleaner suggestion or if @MihaiSurdeanu  you think this is all dumb, we can close the PR w/o merge

These changes are done for the benefit of the webapp display.  They include:
- adding NounPhrase-Inc, -Dec, and -Quant to the taxonomy under NounPhrase
- adding a helper method in the keepMostComplete action that collapses all of these to "NounPhrase" so that only one (most complete) nounPhrase is kept for each span
- adding extra entity types in the brat display stuff (main.js)
- and the whole reason for doing this -- I updated the colors of the display items

### CODE REVIEW

**Comment by kwalcock** [comment]
Well, at some point I'd like to find an alternative for these string comparisons, but now is probably not the time.  It might be good to keep repetitions of values like "#2471A3" to a minimum.  However, if it works, great!  I'll merge (or watch you do it) after you've had some time to read this.

**Comment by bsharpataz** [comment]
OK -- thanks! good tips!  I'd prefer to get @Mihai's OK before it's merged
bc  it drastically changes the look of the visualizer. I can change the
string html color refs to a variable in a subsequent PR?

**Comment by MihaiSurdeanu** [comment]
I would prefer if this wasn't merged in master. In addition of Keith's comments, I would prefer if the taxonomy were agnostic to the state.

**Comment by kwalcock** [comment]
Is it easy to include a screen shot?  I admit to not pulling the branch, rebuilding, etc. to see how it looks.  Maybe it's not necessary now that Mihai has commented.

**Comment by bsharpataz** [comment]
per @MihaiSurdeanu I will refactor this PR and re-submit -- @kwalcock do you prefer for me to close and open a new one? or refactor and push again?

**Comment by kwalcock** [comment]
Whatever is easiest.  I'll find out what "taxonomy were agnostic to the state" means.

**Comment by bsharpataz** [comment]
oh, sorry -- I didn't understand that that was what  you wanted the
screenshot of.  He's referring to my including the -Inc, -Dec, and -Quant
sub-types under NounPhrase.  That is, rather than have just NounPhrase in
the taxonomy all possible states of NP were listed (which is messy and hard
to maintain).  What I will do instead (I think), and your input on this is
welcome, is keep only NP and later when sending the mentions to the
brat-visualizing webapp code I can edit the label of the NP.  I *think*
this will work.... but admittedly am not 100% sure.

**Comment by kwalcock** [comment]
I just meant a picture of how the webapp looks in the browser with the improvements.

**Comment by bsharpataz** [comment]
I made the changes: 
- removed states from taxonomy (etc, e.g. Actions)
- added a "post-processing" step in the webapp to recover the states for brat-json
- moved colors to variables at the top of main.js
- renamed RAPShell to better title

here's a picture, btw:
screen shot 2018-01-29 at 5 38 14 pm

**Pull request merged**
