### PR TITLE
Findgeo

### PR DESCRIPTION
**Pull request by BeckySharp**
Adds Location attachment to Location mentions found with a gazatteer, importantly this includes the geoloc lookup

FYI @bethard @EgoLaparra 
FYI @zupon -- note that I removed the generic "locations" like "settlement" -- we'll have to put those in a separate file (or handle another way) when your branch gets merged in

### CODE REVIEW

**Comment by kwalcock** [comment]
I didn't merge into master yet, but did add this to the branch that is rerunning along with the patched DCT code.

**Comment by BeckySharp** [comment]
cool!

**Comment by maxaalexeeva** [comment]
I merged this into migration_schema-zupon because I really really needed this. This thing has made my week, @BeckySharp!

**Comment by BeckySharp** [comment]
great!

**Comment by kwalcock** [comment]
I'm not sure why this had a yellow dot for so long, but resubmitting the Jenkins job fixed it.  On the one hand the code seems fine and on the other I'm not sure the output was evaluated for improved performance.  I assume that it can be quickly turned off if that's a problem, though.

In some future round perhaps miscellaneous string constants as in `_ matches "Location"` can be organized more like `m matches EidosSystem.COREF_LABEL`.

**Pull request merged**
