### PR TITLE
webapp loading message

### PR DESCRIPTION
**Pull request by marcovzla**
let the user know something is happening

### CODE REVIEW

**Comment by bsharpataz** [comment]
+1 +1 +1

**Comment by kwalcock** [comment]
Cool!  Do you mind if I change the typography a little?  That's a nice n-dash, so I'd like to continue and write alert("Please write something."); and "Reading text..."

These have been great changes recently.  If you have any more in mind I wonder if some planning or prioritizing would be useful.  Perhaps you already discussed it with others or these are ports from something else you're working on, though.  Thanks for the updates.

**Comment by marcovzla** [comment]
Sure, feel free to change anything. I will push another commit to change the textfield into a text area.
@bsharpataz feel free to change anything too.

**Comment by marcovzla** [comment]
I don't really have anything planned. So feel free to make suggestions.

**Comment by kwalcock** [comment]
Changes in the graphic will have to wait for a different PR, I guess.

**Comment by bsharpataz** [comment]
ok -- yes, marco just showed me the funnest site for making/customizing
them, so I will actually prob submit a pr for one later, but my all means
merge w/o that :)

**Pull request merged**
