### PR TITLE
Expansion handler added

### LINKED ISSUE #487: make expansion handler
it should take language as an arg and be used in EidosActions, to allow for PT/ENG specific expansion

### PR DESCRIPTION
**Pull request by bsharpataz**
Ideally to serve as a way to handle english and portuguese differently

EidosSystem now owns one, instantiates it with language (FWIW i imagine that here much code will be reused from Eng/PT, and only some will differ), and EidosSystem passes the ExpansionHandler to EidosActions to use for expansion.

Note -- added a "fixme" in the TestEidosActions class........ (line 149)

@gcgbarbosa FYI and reorganize anything you want as needed now or in the future!!

closes #487

### CODE REVIEW

**Comment by kwalcock** [comment]
So this is a refactoring and doesn't change any output and doesn't need to be merged for this impending release?

**Comment by bsharpataz** [comment]
no -- doesn't change any output (at least I hope not!) and doesn't need to be merged in impending release (but can be!), it WILL facilitate some stuff that @gcgbarbosa is trying to do though, fwiw

**Comment by bsharpataz** [comment]
@kwalcock I fixed the conflicts (and refactored a Geo thing's name  to me more scalarific) @vikas95 fyi

**Comment by bsharpataz** [comment]
@kwalcock -- i have a bugfix/improvement I want to merge in, but i need to merge this one first... any ideas on timeline?

**Comment by kwalcock** [comment]
How about now?

**Comment by kwalcock** [comment]
@vikas95 does have a backlog of other variable names to change as well.

**Pull request merged**
