### PR TITLE
Neg handler

### PR DESCRIPTION
**Pull request by bsharpataz**
Converted negationhandler to a class, currently not super lexical so I didn't make a resource file, though one could certainly be added.  However, the class is initialized with the language from the eidos.conf so lang specific implementations can (and should!) be implemented...

FYI @gcgbarbosa !

### CODE REVIEW

**Comment by kwalcock** [comment]
That's a great idea passing the language to the NegationHandler.  Depending on how that develops, the companion object may want to take that language and create an EnglishNegationHandler or PortugueseNegationHandler, each derived from an AgnosticNegationHandler to take care of common tasks.  There is hopefully only one match statement necessary.

**Comment by kwalcock** [comment]
The test framework has not kept up with the additional attachments and neither have the tests.  At some point don't we need to go through all the tests and next to INC, DEC, and QUANT add TIMEX, HEDGE, NEGATION, and PROP?  Third parties and planning might be involved.  I'd vote for merging this and then scheduling additional rounds.

**Comment by bsharpataz** [comment]
> The test framework has not kept up with the additional attachments and neither have the tests. At some point don't we need to go through all the tests and next to INC, DEC, and QUANT add TIMEX, HEDGE, NEGATION, and PROP? Third parties and planning might be involved. I'd vote for merging this and then scheduling additional rounds.

I agree that we should merge these and then schedule add'l rounds, but I'll add that we may want to wait to make sure that we're happy with the representation (i.e., let the dust settle?)
As long as we're doing extra rounds we should also finish going thru failing tests and see if we can make more of them pass... I only did like 5 or 6 files so there is more to do

**Comment by bsharpataz** [comment]
> That's a great idea passing the language to the NegationHandler. Depending on how that develops, the companion object may want to take that language and create an EnglishNegationHandler or PortugueseNegationHandler, each derived from an AgnosticNegationHandler to take care of common tasks. There is hopefully only one match statement necessary.

@kwalcock can i leave for future PRs when we see how much of the code in the English one is re-usable for the Portuguese (i.e. what can be shared vs language specific?)

**Comment by kwalcock** [comment]
Yes, therefore the "Depending on how that develops"...

**Pull request merged**
