### PR TITLE
4 more tests passing test-doc-7 and test-doc-8.

### PR DESCRIPTION
**Pull request by ajaynagesh**
@bsharpataz : Request you to take a look some of my doubts as Todos in the comments

### CODE REVIEW

**Comment by ajaynagesh** [comment]
Fixing the comments by @bsharpataz. Looks like this can be merged..

**Comment by kwalcock** [comment]
Not so fast... 😆

**Comment by ajaynagesh** [comment]
@kwalcock : had left checked-in a compilation error. Fixed that now

**Comment by kwalcock** [comment]
Is @bsharpataz happy with this now?

**Comment by ajaynagesh** [comment]
@bsharpataz : Could you please approve this PR whenever you get a chance next ?

**Comment by kwalcock** [comment]
@bsharpataz, what should be done with this now?  Has it expired?

**Comment by BeckySharp** [comment]
@kwalcock yeah prob, sorry, but this reminds me that one day we should see if we can make some of the failing tests pass... some may already

**Pull request closed without merging**
