### PR TITLE
Update test grounding

### PR DESCRIPTION
**Pull request by zupon**
This PR
- Adds a new exporter for generating a compositional grounding eval sheet
- Adds "not be incorrect" test as `groundingShouldNotContain` function in `TestGrounding.scala`

### CODE REVIEW

**Comment by zupon** [comment]
@kwalcock Can you take a look at this PR? Checks have failed but I don't think I have the Jenkins credentials handy to see what's going on.

**Comment by kwalcock** [comment]
Here's the error message below.  That merge with master at the very end included a change which requires the config to be passed around.  So the CompositionalGroundingSheetExporter probably needs to accept a config argument and not make its own config.  HTH.  If not, just say.

```
[info] compiling 9 Scala sources to /var/jenkins_home/workspace/eidos_update_TestGrounding/target/scala-2.11/classes ...
[error] /var/jenkins_home/workspace/eidos_update_TestGrounding/src/main/scala/org/clulab/wm/eidos/exporters/Exporter.scala:27:34: not enough arguments for constructor GroundingInsightExporter: (filename: String, reader: org.clulab.wm.eidos.EidosSystem, config: com.typesafe.config.Config)org.clulab.wm.eidos.exporters.GroundingInsightExporter.
[error] Unspecified value parameter config.
[error]       case "groundingInsight" => new GroundingInsightExporter(filename, reader)
[error]                                  ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 31 s, completed Aug 30, 2021 10:41:58 PM
```

**Comment by zupon** [comment]
@kwalcock All checks now pass! Is this good to go?

**Comment by kwalcock** [comment]
Yes, indeed.  Thanks.

**Pull request merged**
