### PR TITLE
Update processors

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by BeckySharp** [comment]
wow! pr 1000! cause for celebration? happy birthday, Eidos!

**Comment by kwalcock** [comment]
This passed the tests on River, but now the tests don't pass on my machines even with 16 or even 32GB configured.  They crash out saying that no more memory is available.

**Comment by MihaiSurdeanu** [comment]
This is most likely caused by the storing of glove embeddings twice, including in the less efficient dynet representation...
I am working on yet another idea that might fix this. ETA <= 1 week, depending on how much actual time to work on it I get...

**Comment by kwalcock** [comment]
I have to take some of that back, especially for the 32GB  The messages I saw were related to the test which specifically exhausts the memory and makes sure eidos recovers.  It was not recovering with 16GB, but that might not be because of the 16GB.

**Pull request merged**
