### PR TITLE
Move SentenceClassifier to EidosComponents

### PR DESCRIPTION
**Pull request by kwalcock**
and then use it in EidosSystem

### CODE REVIEW

**Comment by kwalcock** [comment]
This compiles, but it looks like you might have been having problems with the configuration file.  In any case, it shows how the sentence classification might be added to the pipeline.  The classification seems to be headed to the Mentions rather than the Document and that's the main reason for the move.

**Comment by BeckySharp** [comment]
> LGTM, but maybe @BeckySharp should say it.

fine with me too!

**Comment by kwalcock** [comment]
This PR is not going to master (main), but to a branch so that @zhengzhongliang and I can discuss it momentarily.

**Comment by kwalcock** [comment]
@zhengzhongliang, notice in EidosComponents that
```scala
val sentenceClassifierOpt = SentenceClassifier.fromConfig(config[Config]("sentenceClassifier"), language, ontologyHandlerOpt.get)
```
already uses `sentenceClassifier` so that in SentenceClassifier,
```scala
val idfWeightsFile = config.getString("sentenceClassifier.tokenIDFWeights")
```
probably doesn't need that part.  It can just be `tokenIDFWeights`.

**Comment by zhengzhongliang** [comment]
Got it. Thanks Keith!

Keith Alcock <notifications@github.com>于2020年7月7日 周二下午3:40写道：

**Comment by kwalcock** [comment]
I added untested code to show the sentence classifications being cached.  Even if that all works, I need to eventually update the (de)serialization code to include the classifications, so you haven't seen the last yet.

**Comment by kwalcock** [comment]
So you can merge if you'd like.  I'm done for the time being.  The tests only need to pass before merges into master.

**Comment by zhengzhongliang** [comment]
Thanks Keith, I will merge it to my branch.

Keith Alcock <notifications@github.com>于2020年7月7日 周二下午3:59写道：

**Comment by kwalcock** [comment]
I wrote too soon.  A SentenceClassifier is not always available and I forgot the else branch.  You are welcome to change that logic, of course.

**Pull request merged**
