### PR TITLE
Full ontology tree experiment parent name filtered no root

### PR DESCRIPTION
**Pull request by BeckySharp**
Let's get this merged in so we can re-ground the reader output before the experiment?

fyi @MihaiSurdeanu  @Fan-Luo

### CODE REVIEW

**Comment by kwalcock** [comment]
This branch is not meant for checking into master and I should delete the PR.  It is the base branch for the grounding experiments.  useW2V = true cannot be used in the master branch because we can't test or run with w2v.  Full caching cannot be used with the grounding experiments because the ontology caching was highly optimized and doesn't support the operations needed for the experiments.  If master needs to be cacheable, then the compact ontology representation needs to be reworked.  I believe the code here was hacked so that the vector file could still be cached while the ontologies wouldn't be.  It might not be possible to use a configuration setting for parents on/off and still cache in as an efficient manner as previously.  The code used for the recent reading is in DART-42k* and includes some of this code.  It should be able to reground.

**Comment by BeckySharp** [comment]
OK -- so then we'll need to reground?  I looked on the DART4-42k* branches and it seems that DART4-42k-B and DART4-42k-B1532 both have the parentName grounding implemented, 
(a) was the latest output we sent to Ben run with one of these branches and if so, was this non-leaf node grounding activated? thanks!

**Comment by BeckySharp** [comment]
I think so -- since we got "conflict" as one of the groundings -- thanks!

**Comment by kwalcock** [comment]
It was at least intended that grounding was activated and to the flattened version at that, and not to the props at all.  I did some checks that indicated that the settings were effective.

**Comment by BeckySharp** [comment]
Awesome, thanks!

**Pull request closed without merging**
