### PR TITLE
Test the migration events

### PR DESCRIPTION
**Pull request by kwalcock**
Here's a first draft.  Merge if desired to your branch.

### CODE REVIEW

**Comment by BeckySharp** [comment]
well good grief @kwalcock -- that was fast!

**Comment by kwalcock** [comment]
Do these need to be jsonld'd before the hackathon so that something can make use of them?  We discussed adding some kind of grouping function to combine the Odin event mention(s) into maybe a special kind of Eidos event.  I'm not sure that applies to the present design, though.  I would at least have to do some special things to export all those arguments and give them names, etc. to fit into the design described on https://github.com/clulab/eidos/wiki/Anatomy-of-Mentions.  I would probably be looking for an Event with a label of HumanMigration and then raiding and renaming the arguments, etc.

**Comment by MihaiSurdeanu** [comment]
Yes, we need the json output for these events. Your assumptions are correct.
Thanks!


________________________________

**Comment by kwalcock** [comment]
OK, then I'm starting an issue #594 for details of the format.

**Comment by kwalcock** [comment]
These latest changes provide provisional jsonld support so that you can get see some output.  It certainly doesn't read it back in yet.

**Pull request merged**
