### PR TITLE
expanded ontology by Fan

### PR DESCRIPTION
**Pull request by Fan-Luo**

### CODE REVIEW

**Comment by kwalcock** [comment]
@Fan-Luo, you beat me to this.  I think I have to merge mine first so that the code to read this new format is in place and then add your improvements.  However, what is with December?  We keep losing it off the end of the file, or is it supposed to be missing?

**Comment by Fan-Luo** [comment]
December was not there when I got it, but added now.

**Comment by Fan-Luo** [comment]
'fertilizer' and 'irrigation' under human?

**Comment by kwalcock** [comment]
@Fan-Luo, I think you'll want to use all of your changes.  I hope that resolving kicks off another unit test to make sure the new file passes the tests.  I'll check in a few hours when I get back.

**Comment by kwalcock** [comment]
Thanks, @Fan-Luo, for merging.

**Comment by kwalcock** [comment]
I hope everyone found the most recent copy, whatever or wherever it is.

**Comment by Fan-Luo** [comment]
For merging, I simply overwrite as you said use all of my changes. 
Not sure whether it is right thing to do. Please check, thanks

**Pull request merged**
