### PR TITLE
Clean up adjective grounding

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
The example on the readme page will changes from

```scala
  // Export to JSON-LD
  val corpus = new JLDCorpus(Seq(annotatedDocument), reader.loadableAttributes.adjectiveGrounder)
  val mentionsJSONLD = corpus.serialize()
```
to
```scala
  // Export to JSON-LD
  val jsonld = new JLDCorpus(annotatedDocument).serialize()
```

**Comment by kwalcock** [comment]
This addresses #783.  Adjective grounding can be turned on and off in the configuration file.  The adjective groundings have been added to TriggeredAttachments.  EidosSystem does a pass over the EidosMentions to perform the grounding if it is configured.  The serializer just serializes what it has and doesn't do any additional processing.  Lots of apps and examples have been simplified.

I just remembered that the deserializer needs to be updated, so stand by.

**Comment by kwalcock** [comment]
@bgyori, do you ever call serialize on a JLDCorpus or other JLDObject with an adjectiveGrounder?  The need, and also the ability, to do that is being removed.  EidosSystem knows enough to do that on its own with this PR.

**Comment by bgyori** [comment]
The adjectiveGrounder will not affect what we do, however, the fact that 
```
JLDCorpus(Seq(annotatedDocument))
```
will change to 
```
JLDCorpus(annotatedDocument)
```
will need to be changed in INDRA after this is merged.

**Comment by kwalcock** [comment]
Oops, maybe.  A Corpus is a Seq[AnnotatedDocument], so at least from Scala we can still call
```Scala
JLDCorpus(Seq(annotatedDocument))
```
through
```Scala
def this(corpus: Corpus) = this(new JLDSerializer, corpus)
```
Will it not work from Python?

**Comment by kwalcock** [comment]
That seems to be the only one that has ever been available, through a Corpus.  There was never explicitly one for a Seq[AnnotatedDocument].  I don't *think* you have need to change code.

**Comment by bgyori** [comment]
Alright, in that case we may not need to do anything further on our end. Thanks!

**Pull request merged**
