### PR TITLE
Cross compilation for scala 2.11 and 2.12

### PR DESCRIPTION
**Pull request by marcovzla**
This PR adds cross-compilation to the release process so that two artefacts are published, for scala 2.11 and 2.12. Depends on clulab/processors#237

### CODE REVIEW

**Comment by marcovzla** [comment]
Tests will fail until a cross-compiled version of processors is released. Please do not merge yet.

**Comment by kwalcock** [comment]
I'm about to check something in using 7.2.2.  That part seems to work well.

**Comment by kwalcock** [comment]
There is code which is incompatible with Scala 2.11.11.

**Comment by kwalcock** [comment]
It is very likely code that I added without knowing of any requirement for backward compatibility.

**Comment by kwalcock** [comment]
Will this then double the time that Travis needs to run its tests?  That would be unfortunate.

**Comment by marcovzla** [comment]
The tests should run in parallel

**Pull request merged**
