### PR TITLE
Migration schema zupon

### PR DESCRIPTION
**Pull request by maxaalexeeva**
There are still quite a few things to fix about the migration branch, but there are already only 49 migration tests failing (ignored) out of 208, so it might be presentable enough (and it's getting harder to maintain). There have been a few master merges, and while I don't think anything important from master got damaged, would you @BeckySharp and @kwalcock have a look? Thank you!

### CODE REVIEW

**Comment by maxaalexeeva** [comment]
I guess we'll also see if the tests here pass..

**Comment by kwalcock** [comment]
It's just complaining about
```
[info] migration_settle
[info] - should have correct group1 node
[info] - should have correct moveTo1 node
[info] - should have correct migration1 event *** FAILED ***
[info]   List("Could not find EdgeSpec HumanMigration->(group: [IDPs])->(moveTo: [Bor Town|+GEO(Bor Town)])", "Mentions:
```

**Comment by maxaalexeeva** [comment]
@kwalcock, thank you! I will check on that soon.

**Comment by maxaalexeeva** [comment]
Hi @BeckySharp, 

I have two tests failing in this branch locally that pass in master, but I can't figure out why---in the webapp the outputs look similar. Here are the failing tests:

Failed tests:
[error] 	org.clulab.wm.eidos.text.english.eval6.TestDoc5
[error] 	org.clulab.wm.eidos.text.english.cag.TestCagP2

Do you think you could have a look when you have a minute? Thanks!

@MihaiSurdeanu, when the issue above is resolved, do you want this branch merged? Becky recently solved the issue we were having with the geoloc normalizer, so the branch looks decent (163 migration event tests succeed, 43 ignored).

**Comment by maxaalexeeva** [comment]
@BeckySharp, one more thing:
Both in master and the migration branch, _South Sudanese_ is found as Location, but it is only in the migration branch that this location attaches to this mention (not in master):
https://github.com/clulab/eidos/blob/c8b70a6aa123350ba78bce02040a6ca244fb1398/src/test/scala/org/clulab/wm/eidos/text/english/eval6/TestDoc5.scala#L152
That's why the test fails, I think, but I am not sure why the location attaches in one case, but not in the other.

**Comment by kwalcock** [comment]
I'll be looking it over pretty soon just in case there is any weirdness to notice.  Maybe you found some above.  It's also likely the case that the deserialization of migration events is not complete and is waiting for me.  If this branch includes the change from lazy val to var in EidosMention, then I need to work on the side effects of that as well, not that either of these affects the reading directly.

**Comment by BeckySharp** [comment]
I'll def take a look, thanks!

**Comment by BeckySharp** [comment]
@masha -- is this still the case?  Bc recall that I had made that screw up
so the master before the very-recent patch merge didn't have the nmod:poss
commented out in the excluded deps.

**Comment by BeckySharp** [comment]
ok, i'll check it out, thanks!

**Comment by kwalcock** [comment]
I have been waiting for that last test to pass or be disabled before looking too closely at this.

**Comment by maxaalexeeva** [comment]
@kwalcock, sorry, I misunderstood what you said before about looking at the branch---I thought you could have a look at the branch even with the two tests failing. I talked to @BeckySharp earlier today and she was not sure off the top of her head why the two tests are failing. We will have to get back to this next week or the week after that. Sorry about the delay.

**Comment by kwalcock** [comment]
Yes, I can look.  Just can't finish, not that I've started.

**Comment by kwalcock** [comment]
@zupon, is the branch migrationNormalizingGeolocs-zupon a dead end, not needing to be in master?  Can it be deleted?

**Comment by kwalcock** [comment]
@BeckySharp, @zupon, it seems necessary to (de)serialize this CrossSentenceEventMention.  I *think* that it will be serialized as its superclass, EventMention, and that's what it will be deserialized as.  Is there a way I can identify it during deserialization to route it to its real class (without messing up the JLD)?

**Comment by zupon** [comment]
> 
> 
> @zupon, is the branch migrationNormalizingGeolocs-zupon a dead end, not needing to be in master? Can it be deleted?

@kwalcock I believe that it can be deleted. That branch was a stub that we started as a placeholder for grounding geolocations in the future, but @BeckySharp did something cool and made it just work in the `migration_schema-zupon` branch, so the `migrationNormalizingGeolocs-zupon` became unnecessary. Does that sound correct, @BeckySharp and @maxaalexeeva ?

**Comment by maxaalexeeva** [comment]
Confirm.

**Comment by kwalcock** [comment]
@maxaalexeeva, there are still some todos in CrossSentenceEventMention.  Do they need to be addressed?  Should I include the trigger, for example?  The question above may apply more to you than I realized yesterday.

**Comment by kwalcock** [comment]
I'm concerned about a few things so far:

In MigrationUtils.mergeArgs, sometimes the new arguments are taken from mention1 and sometimes from mention2 (if I understand it correctly).

In MigrationUtils.assembleFragments, the ordering of the mentions is not preserved.  The incoming mentions get ordered, but the ordering of returnedEvents is not guaranteed.

I'm rewriting some code and wonder what the older code really means and request clarification.

**Comment by BeckySharp** [comment]
sorry I didn't see this question earlier!  I think that all of the
CrossSentenceMentions are likely of a couple of Labels.... would that
work?  Alternatively maybe we can co-opt the Attachment to carry the
information, but that's a hack...

**Comment by kwalcock** [comment]
There were two tests still failing.  Should I just disable them?

**Comment by maxaalexeeva** [comment]
> @maxaalexeeva, there are still some todos in CrossSentenceEventMention. Do they need to be addressed? Should I include the trigger, for example? The question above about serialization of the subclass may apply more to you than I realized yesterday.

@kwalcock, I think this one: https://github.com/clulab/eidos/blob/ad5f4b9867a509d2420c98b28afb8006ac62fdb9/src/main/scala/org/clulab/wm/eidos/mentions/CrossSentenceEventMention.scala#L27 has been addressed based on this output (all the clauses are included when the text of the mention is printed out):
Screenshot from 2019-12-04 22-06-32
Screenshot from 2019-12-04 22-06-45

About including the trigger: for CrossSentenceEventMention text, I am not sure if we want the span all the way up to the trigger. Here is an example:

Screenshot from 2019-12-04 22-17-36

@BeckySharp, do we want the text of the mention be "South Sudan ; they left the country for Ethiopia . It was in 1997" or "South Sudan ; they left the country for Ethiopia . It was in 1997 that they left."? 

This one below we probably can't address yet, can we, if all the token intervals are based on the sentence and not full text?
https://github.com/clulab/eidos/blob/ad5f4b9867a509d2420c98b28afb8006ac62fdb9/src/main/scala/org/clulab/wm/eidos/mentions/CrossSentenceEventMention.scala#L11

Not sure why we added the "place elsewhere" there. Seems to be a reasonable place for it along with the other mentions?
https://github.com/clulab/eidos/blob/ad5f4b9867a509d2420c98b28afb8006ac62fdb9/src/main/scala/org/clulab/wm/eidos/mentions/CrossSentenceEventMention.scala#L10

**Comment by maxaalexeeva** [comment]
> There were two tests still failing. Should I just disable them?

@BeckySharp, do you want to look at the two tests on Friday? I don't think you wanted any tests disable, is that right?

**Comment by BeckySharp** [comment]
Yes, if I don't today.  I'm trying to catch up on old business today.  In
terms of the text of the mention, it should have both sentences, and I
think there was a way, I'll check into it. Can you please send me the
pointer to where you're making the mention, in case I can't easily find it?
And should I just checkout out that commit hash? or is there a branch I
should use?

**Comment by maxaalexeeva** [comment]
> Yes, if I don't today. I'm trying to catch up on old business today. In terms of the text of the mention, it should have both sentences, and I think there was a way, I'll check into it. Can you please send me the pointer to where you're making the mention, in case I can't easily find it? And should I just checkout out that commit hash? or is there a branch I should use?

@kwalcock, the latest changes you made to migration were not on this branch, were they?

> In terms of the text of the mention, it should have both sentences, and I think there was a way, I'll check into it.

This is where the text method is overwritten for crossSentenceEventMentions and I think it works correctly except for the inclusion of the span all the way up to the trigger (it now just gets the span between the leftmost arg and the rightmost arg): https://github.com/clulab/eidos/blob/ad5f4b9867a509d2420c98b28afb8006ac62fdb9/src/main/scala/org/clulab/wm/eidos/mentions/CrossSentenceEventMention.scala#L28

**Comment by kwalcock** [comment]
I haven't added any changes to this branch recently.  I'll have some ready shortly, though.

**Comment by kwalcock** [comment]
The way to do this is probably just to check whether any of the arguments come from different sentences.  I'm slowly catching on.

> @BeckySharp, @zupon, it seems necessary to (de)serialize this CrossSentenceEventMention. I _think_ that it will be serialized as its superclass, EventMention, and that's what it will be deserialized as. Is there a way I can identify it during deserialization to route it to its real class (without messing up the JLD)?
> 
> If that's not possible and since text is the only override, it may be possible to combine the class with the superclass so that the deserializer need not distinguish.

**Comment by kwalcock** [comment]
@BeckySharp, can a CrossSentenceMention ever get involved in MentionUtils.copyWithNewArgs?

**Comment by BeckySharp** [comment]
I don't know...... maybe? at the very least we should handle it, i.e. crash
or fail with an elegant warning, etc
the cross-sentence mention is for the coref stuff and migration only, I
think. the copy with new args works over, what, expansion?

**Comment by kwalcock** [comment]
I have left in two anomalies because they affect the tests and I didn't yet want to break a test without figuring out what exactly is happening.  In assemble Fragments I am letting the once ordered Mentions become unordered and in mergeArgs I am not doing an honest comparison.  I had to back off my changes in these places to pass regression tests.  Even so, output of three files changed just slightly and I haven't been able to account for it.  I hope it is just some ordering issue.  I'm running the DART data with this version, even though it is not yet in master.

**Comment by maxaalexeeva** [comment]
@kwalcock, I'll check how essential it is this afternoon. If I remember correctly, it was there to make sure that modifiers like 'daily' (e.g., daily average arrival rate of 300 people) are sure to end up within the migration mention span, but there's a chance, they end up inside the span even without that argument, so we might not need to keep it.

**Comment by kwalcock** [comment]
Keeping it is fine, as long as it is also output.  I hope someone can clarify sooner.  We're on the verge of missing a deadline.

**Comment by maxaalexeeva** [comment]
@kwalcock, currently, there's one example where having the group modifier helps to get the right information about the rate of arrival, so my first choice would be to keep it. In this example, without the groupModifier, the word _daily_ is not in the mention span, so it does not get picked up by https://github.com/clulab/eidos/blob/0ccd8150058dedf51ff04857bd07681336cce433/src/main/scala/org/clulab/wm/eidos/EidosActions.scala#L88:
      
Screenshot from 2019-12-12 11-19-35

I don't know much about how output works, so I can't make a decision there. @BeckySharp?

**Comment by kwalcock** [comment]
This branch was used in the most recent reading and worked well, so I'm about to merge it into master.  Thanks @maxaalexeeva, @zupon, and others for working so hard on it.

**Comment by MihaiSurdeanu** [comment]
Yay!


On January 8, 2020 at 9:07:27 AM, Keith Alcock (notifications@github.com)
wrote:

Merged #700 <https://github.com/clulab/eidos/pull/700> into master.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/eidos/pull/700?email_source=notifications&email_token=AAI75TXM7XBTBDZKGLHFTZLQ4X237A5CNFSM4JE7JM22YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOV275BWI#event-2931806425>,
or unsubscribe

**Comment by BeckySharp** [comment]
Awesome! Thanks!!

**Comment by maxaalexeeva** [comment]
Thank you, @kwalcock!!

**Pull request merged**
