### PR TITLE
Make a SimpleEidos object to configure Eidos

### PR DESCRIPTION
**Pull request by kwalcock**
SimpleEidos.newEidosSystem(useGeoNorm: Boolean, useTimeNorm: Boolean): EidosSystem should get an appropriate "simplified" eidos.

### CODE REVIEW

**Comment by kwalcock** [comment]
I'm not sure who this is for and it doesn't necessitate any changes to Eidos proper, so I'll PR it to master and tag Mihai.  It's only about 25 lines of code without the sample main, and could be packaged in lots of other ways.  This is the gist of it though.

**Comment by MihaiSurdeanu** [comment]
- I would recommend adding an `apply` method to SimpleEidos to make the construction trivial.
- Also, would it be possible to add a simple output format as well? That is, a format that focuses on the triple cause/relation/object, with some provenance as well (sentence and offsets)?

**Review by MihaiSurdeanu — APPROVED** [review]

**Comment by kwalcock** [comment]
The first change was straightforward.  It is a little bit deceptive because one might expect a SimpleEidos to be returned, but one gets a full-fledged EidosSystem instead.  Example output is forthcoming.  That seems like a something that will change often based on refined needs.

**Comment by kwalcock** [comment]
I'll add output in a new PR.

**Pull request merged**
