### PR TITLE
Try a fix for issue #262

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
This probably isn't quite ready and should have some tests.  The first time we did this I was just happy to get the merge to work.  I left in at least one TODO.  AFAIK, filterAttachments returns multiple attachments in the order it received based on the keys of a groupBy function.  It is not clear to me that the first one should be chosen to locate the "template".  It's unfortunate that we don't have a good Mentions constructor for this case and that the attachments have to be added on.  I think that the existing ones may need to be removed before the winners are added back... unless it is important to keep the other ones because they are guaranteed to match the rule used and other internal data.  Maybe .head should just be replaced by something better then.

**Comment by kwalcock** [comment]
This is the draft for which I will write a few simple sanity checks.

**Comment by kwalcock** [comment]
OK, @bsharpataz @ZhengTang1120 I'm ready to let this go.  You might want to take a quick look to see if it still does what you intended.

**Comment by bsharpataz** [comment]
OK -- I'll run some sentences thru tomorrow -- but it doesn't crash on that
doc anymore I presume?

**Comment by kwalcock** [comment]
Not on my computer ;-)  All the tests still pass, but it might get different answers on some edge cases.

**Comment by bsharpataz** [comment]
yep!  still does what we wanted, so yay, let's merge and see how long it takes for the next bug! :)

**Comment by kwalcock** [comment]
Good point.  I should spell those out then: less than and greater than or equal.  Maybe it should have been ge.  I'll change it.  Doesn't everyone learn assembly language?

**Comment by kwalcock** [comment]
I spelled them out.  This code will soon move to the Attachment class as a compareTo function, I think.  Some Attachments are inherently bigger than others.

**Pull request merged**
