### PR TITLE
Import vars

### PR DESCRIPTION
**Pull request by bsharpataz**
ok... well... in this PR really is that I am importing vars.... and I added a constraint on a rule.  I also deleted a few old grammar files and fixed a "bug" in which the compositionality of the foundBy was being lost w/ subsumed attachments.  *BUT* it looks like a lot more bc I merged the webapp_grounding branch into this to get access to a rule update.  If we merge that one first, it will look like a lot fewer files changed...

also, @kwalcock I am having trouble with this:

```[info] *** 1 SUITE ABORTED ***
[error] Error during tests:
[error] 	org.clulab.wm.eidos.system.TestResources
[error] (core/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 91 s, completed Jul 14, 2018 2:54:27 PM
```

can you help? I really don't know what is making it fail...
Here's the trace:
```[info] TestResources:
[info] org.clulab.wm.eidos.system.TestResources *** ABORTED ***
[info]   java.nio.charset.MalformedInputException: Input length = 1
[info]   at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
[info]   at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
[info]   at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
[info]   at java.io.InputStreamReader.read(InputStreamReader.java:184)
[info]   at java.io.BufferedReader.read1(BufferedReader.java:210)
[info]   at java.io.BufferedReader.read(BufferedReader.java:286)
[info]   at java.io.Reader.read(Reader.java:140)
[info]   at scala.io.BufferedSource.mkString(BufferedSource.scala:94)
[info]   at org.clulab.wm.eidos.system.TestResources.test(TestResources.scala:17)
[info]   at org.clulab.wm.eidos.system.TestResources.$anonfun$new$1(TestResources.scala:47)
[info]   ...
```

### CODE REVIEW

**Comment by bsharpataz** [comment]
closes #141

**Comment by bsharpataz** [comment]
@kwalcock why did this pass? it failed locally on the thing I mentioned in the comments...???

**Comment by kwalcock** [comment]
I'll check.  It's probably something about the encoding that is different on your machine than on Travis in addition to some weird character.

**Comment by bsharpataz** [comment]
Hmmm, ok, thanks, I’ll check.... ok then, good to go on the PR whenever!

**Pull request merged**
