### PR TITLE
Extract and ground canonicalNames for experiment

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
We may not want to merge this PR with this branch, in part because there are experimental things here which we don't want directly in master.  However, this does show what needed to be changed in the fullOntologyTree.  Perhaps another, experimental branch, should be made.

**Comment by kwalcock** [comment]
Of 279962 extractions, 146456 are grounded to leaf nodes and 131451 to branch nodes.  I can send the output to anyone for analysis.

**Comment by kwalcock** [comment]
I will make this into a new branch and then put the output on a google drive for analysis.

**Comment by kwalcock** [comment]
Output is in the shared google drive folder https://drive.google.com/open?id=1P72UPKhJco_tLHRTQv4qBFwO40d5hCFk that you can hopefully edit.

**Comment by kwalcock** [comment]
There is a branch fullOntologyTree-experiment that we should be able to use for experimentation.  Let's do a checkout of that and then branch from it and back to it.

**Comment by BeckySharp** [comment]
hey -- so what branch are we using for grounding?
we need to be able to ground to non-leaf nodes for January's run...

**Comment by kwalcock** [comment]
We have various experimental branches named fullOntologyTree-experiment*.  The branches and tags used for the most recent run were DART-42k*.  I need to clean up a little.  There are still bug fixes from timenorm to be finalized.

**Comment by kwalcock** [comment]
I'm not sure what you mean by January's run.  As far as I know, we aren't rerunning anything.

**Comment by BeckySharp** [comment]
> I'm not sure what you mean by January's run. As far as I know, we aren't rerunning anything.

yes -- sorry, I meant the runs we already did for the January experiment -- there was an ontology mix up on another thread and I was worried for a min that we weren't using the non-leaf grounding bc it wasn't in master, and i had promised we would :) sorry!

**Comment by kwalcock** [comment]
I'll close the PR so that it confuses fewer people.  The branch is still available to spawn other experiments.

**Pull request closed without merging**
