### PR TITLE
Use mkDocument instead of entire annotate

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
This brought the time for one test down from 8 minutes to 3 minutes and it used noticeably less memory.  That's at least the right direction.  This is for after the impending release, just in case.

**Comment by bsharpataz** [comment]
Works at least for now, and if we want more annotation than just POS we can add.  Is the 3 mins including time to load the vectors?  If so, we can def work on that

**Comment by bsharpataz** [comment]
Specifcally, @marcovzla suggested a way to... index? the vectors

**Comment by kwalcock** [comment]
Thank you!

**Comment by kwalcock** [comment]
@MihaiSurdeanu, is this any better?  It may eventually need to be handled by processors.

**Pull request merged**
