### PR TITLE
Fiddle with EidosSystem

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
I didn't mean to go down this rabbit hole.  One thing led to another.  This is better documented.  I used the term "refine" because process is too overloaded.  It can be changed.

**Comment by BeckySharp** [comment]
this is so beautiful!!!!

**Comment by bgyori** [comment]
I hate to be a party pooper, I think the changes are nice, but the API of EidosSystem is changed in a way that might break integration with INDRA. I'll try to see if there are any issues and will post an update here on what I find.

**Comment by kwalcock** [comment]
Who is that lurking?  Let me know if you find problems.  I tried to be careful, but may have broken something.

**Comment by bgyori** [comment]
Just tested it, and it looks like you anticipated this issue by implementing
```
   // Legacy versions                                                            
   def extractFromText(                                                          
     text: String,                                                               
     cagRelevantOnly: Boolean = true,                                            
     dctStringOpt: Option[String] = None,                                        
     idOpt: Option[String] = None                                                
   ): AnnotatedDocument = {                                                      
     extractFromText(text, EidosSystem.Options(cagRelevantOnly), Metadata(this, dctStringOpt, idOpt))
   }                                                                             
```
which is the interface INDRA currently uses. This seems to work well, thanks!

**Comment by kwalcock** [comment]
I'll be doing some regression testing yet and merging.  Thanks for checking it out.

**Comment by kwalcock** [comment]
Here goes.

**Pull request merged**
