### PR TITLE
crop and crop technology

### PR DESCRIPTION
**Pull request by ajaynagesh**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
I think both crop and crop_technology should be cleaned up more. For example, I don't think these belong to crop: yield, crop yield, stock, feed, hectare, seedling, produce.
@bsharpataz: can you please do a pass?

**Comment by ajaynagesh** [comment]
Removed some of the crops. Not sure how to clean up crop_technology ... should I remove it altogether ?

**Comment by bsharpataz** [comment]
um... idk bc not an SME but maybe something like:
```+    - crop_technology:
        - pesticide:
            - pesticide
        - harvest:
            - harvesting
 +          - post-harvest
 +          - harvest
        - planting:
          - tillage
          - planting
 +      - systems_sectors:
            - food system
 +          - farmer organization
 +          - department agriculture
 +          - aquaculture sector
            - farming system
 +          - agriculture organization
            - Peoples food system
            - investment agriculture
            - horticulture
            - farming
 +          - cultivation
        - fertility:
            - soil fertility
 +          - fertility
```

and that leaves 
```
- food product
- rice production
 ``` 
to be fit in somewhere else...?

**Comment by MihaiSurdeanu** [comment]
Makes sense!

**Comment by ajaynagesh** [comment]
Will open a new pull request. Closing this. Will address the comments in a new set of pull requests...

**Pull request closed without merging**
