### PR TITLE
Stopfilter

### PR DESCRIPTION
**Pull request by bsharpataz**
the moving filtering methods to OntologyGrounder

### CODE REVIEW

**Comment by kwalcock** [comment]
@ajaynagesh This has been checked in and will probably help with the New Zealand and FAO problem.  I am still writing tests for it, though.

**Comment by bsharpataz** [comment]
sure -- yeah with this as a record of our decision

**Comment by kwalcock** [comment]
Sorry to nag.   Was the conclusion to do stopword filtering before the finding events?  So, in "Australia causes kiwi production." we filter out Australia before it can be used in the causal relationship.  Is that correct?

**Comment by bsharpataz** [comment]
yes -- it happens here:
https://www.dropbox.com/sh/ncx9kpqxkzxr865/AADSgizBCNhI-cALSnn1XCQOa?dl=0

**Pull request merged**
