### PR TITLE
filter extractions with likely misparsed triggers

### PR DESCRIPTION
**Pull request by BeckySharp**
I noticed that in certain situations, some adjs were misparsed, and so they ended up triggering a causal event when they shouldn't.
Example: "Concurrently , female holders have limited access to extension and advisory services." (the original sentence was longer).

I made a filter and added a test, which passes... but I am unsure about the consequences.
I'd like to (a) see if the tests pass, and (b) perhaps have someone (me? other?) check the differences on a small-med set of docs, hand check a sample, and see if it's a net good change.

### CODE REVIEW

**Comment by BeckySharp** [comment]
thanks jenkins!
ok, working on:
```Failed tests:
[error] 	org.clulab.wm.eidos.text.english.eval6.TestDoc5
[error] 	org.clulab.wm.eidos.text.english.eval6.TestDoc3
```

**Comment by kwalcock** [comment]
Regarding TestDoc3, see #978.  It may not be your fault.  It was failing intermittently as recently as last night.  Of course if you can figure out why it's unstable, that would be great, too.  I may get to it as part of the testing framework revision.

**Comment by BeckySharp** [comment]
> Regarding TestDoc3, see #978. It may not be your fault. It was failing intermittently as recently as last night. Of course if you can figure out why it's unstable, that would be great, too. I may get to it as part of the testing framework revision.

to bump this -- any news?

**Comment by kwalcock** [comment]
I *think* this was solved yesterday with https://github.com/clulab/eidos/pull/1006.

**Comment by BeckySharp** [comment]
> I _think_ this was solved yesterday with #1006.

can we trigger a retry on the tests?

**Comment by kwalcock** [comment]
The change in master would need to be merged into jj_triggers, I think.

**Comment by kwalcock** [comment]
Otherwise the test result might not change.

**Comment by BeckySharp** [comment]
@kwalcock what happened to jenkins?

**Comment by kwalcock** [comment]
It is overloaded with 6 jobs in the queue.  I may also have duplicated what you just did.  I only cherry picked the two changes, but it looks like you merged in master.  Sorry.  It will keep Jenkins busy for longer than normal.

**Comment by BeckySharp** [comment]
looks like it passes, are we good to merge @MihaiSurdeanu ?

**Comment by MihaiSurdeanu** [comment]
Yep!

**Comment by BeckySharp** [comment]
ping @kwalcock :) :)

**Comment by kwalcock** [comment]
Thanks for the reminder.

**Pull request merged**
